Use a separate staging table when importing
HSLdevcom/jore4-jore3-importer pull request #12
Opened 2021-06-10 08:49 UTC by lassemaatta

- Apply insert/update/delete in a single query using
  Common Table Expressions
- See discussions such as https://stackoverflow.com/a/42217872
  related to the issue with upsert when dealing with
  lots of data
- Note: link points are fetched after links are committed
  - assigning the initial link points to new links will
    modify the links and thus rows will added to the
    links history table
  - (This will be fixed in a later commit)
- Also, note the difference between ImportableFoo and
  PersistableFoo:
  - The former is used with the ImportFooRepositories
  - The latter is used with the FooRepositories
  - At the moment they are similar, but later when we
    add foreign key constrains they will differ

2021-06-10 17:00 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12)* status: 0 of 53 files reviewed, 1 unresolved discussion (waiting on @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/node/support/NodeImportRepository.java, line 96 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbqqxUU5OYXZn5kiuox:-MbqqxUU5OYXZn5kiuoy:b1klpyh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/main/java/fi/hsl/jore/importer/feature/batch/node/support/NodeImportRepository.java#L96)):*
> ```
> .onConflictDoNothing()
> ```

Reminder for myself: check if this is faster if we replace `ON CONFLICT DO NOTHING` with something like `WHERE NOT EXISTS (SELECT 1 FROM TARGET_TABLE T WHERE T.INFRASTRUCTURE_NODE_EXT_ID = STAGING_TABLE.INFRASTRUCTURE_NODE_EXT_ID)`


<!-- Sent from Reviewable.io -->

2021-06-11 06:08 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12)* status: 0 of 53 files reviewed, 1 unresolved discussion (waiting on @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/node/support/NodeImportRepository.java, line 96 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbqqxUU5OYXZn5kiuox:-MbteNJ_9mtPLxQeODWN:b-c0xwgt) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/main/java/fi/hsl/jore/importer/feature/batch/node/support/NodeImportRepository.java#L96)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> .onConflictDoNothing()
> ```

Reminder for myself: check if this is faster if we replace `ON CONFLICT DO NOTHING` with something like `WHERE NOT EXISTS (SELECT 1 FROM TARGET_TABLE T WHERE T.INFRASTRUCTURE_NODE_EXT_ID = STAGING_TABLE.INFRASTRUCTURE_NODE_EXT_ID)`
</blockquote></details>

Using `WHERE NOT EXISTS` gives a modest performance boost (up-to 10x performance for the commit step but only ~15% gain overall) but more importantly `ON CONFLICT DO NOTHING` may accidentally hide duplicates in the input data (e.g. multiple route directions for the same route and direction but with overlapping dates!). => I'll update this commit to use `WHERE NOT EXISTS`


<!-- Sent from Reviewable.io -->

2021-06-11 06:15 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12)* status: 0 of 53 files reviewed, 2 unresolved discussions (waiting on @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/node/support/NodeImportRepository.java, line 152 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbthPWv53x5leDGOQWn:-MbthPWw9p3B_Bal95ZK:btqcvs7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/main/java/fi/hsl/jore/importer/feature/batch/node/support/NodeImportRepository.java#L152)):*
> ```
> .notIn
> ```

Also, replace this with `NOT EXISTS`.


<!-- Sent from Reviewable.io -->

2021-06-11 08:59 UTC, jarkkoka requested changes
> Reviewed 53 of 53 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12)* status: 51 of 53 files reviewed, 16 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepository.java, line 152 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-Mbq8LEX8EMqzswlvCl-:-Mbq8LEX8EMqzswlvCl0:bpj39bu) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/main/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepository.java#L152)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>         final String actualSql = String.format("with %s as (%s), %s as (%s), %s as (%s) %s",
>                                                inserted.getName()[0],
>                                                insertSql,
>                                                updated.getName()[0],
>                                                updateSql,
>                                                deleted.getName()[0],
>                                                deleteSql,
>                                                unionQuery.getSQL());
> ```
</details>


Quite a query composition. Had to look at it thoroughly. Nice job anyway!
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/util/IImportRepository.java, line 67 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbqCFJS-QKtJtJeDOZW:-MbqCFJS-QKtJtJeDOZX:biij3ay) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/main/java/fi/hsl/jore/importer/feature/batch/util/IImportRepository.java#L67)):*
> ```
> strem
> ```

stream
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/dto/ImportableLink.java, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbuBIAR9fhb0zsFR3cl:-MbuBIAR9fhb0zsFR3cm:b1y991c) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/dto/ImportableLink.java#L10)):*
> ```
> ImportableLink
> ```

Could you add any comment at class level what is ImportableLink vs PersistableLink? The meaning and difference of these interfaces is not very obvious.
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/node/dto/ImportableNode.java, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbtWYrcB9WmK7PdKjDt:-MbtWYrd3MfLa0Obq6JZ:b-qoy6a5) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/main/java/fi/hsl/jore/importer/feature/infrastructure/node/dto/ImportableNode.java#L10)):*
> ```
> CommonFields
> ```

There exists multiple CommonFields interfaces (one for nodes, another for links). This specific CommonFields is for nodes. Still it requires a generic type argument. I would have preferred distinct names like CommonNodeFields and CommonLinkFields. What's your opinion on "overloaded" interface names?
___
*[src/test/java/fi/hsl/jore/importer/config/jobs/ImportLinksStepTest.java, line 60 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbtYvag0K7Zmn1zAK55:-MbtYvahD9YLE1u_NUe_:bxspuxh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f73f704de6ac9e439df48359c912fc9de093e55e/src/test/java/fi/hsl/jore/importer/config/jobs/ImportLinksStepTest.java#L60)):*
> ```
> testUpdatingExistingLink()
> ```

Hmmm...processing got more complex but tests got reduced. But I think it is okay, because here it is essential to test that interaction with database through repository has occurred.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java, line 83 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbuDNrC3RipEg8-PL4z:-MbuDNrC3RipEg8-PL5-:b-6jdyqn) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java#L83)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>         assertThat("Target repository should contain a single row",
>                    targetRepository.count(),
>                    is(1));
>         final Optional<Link> maybeLink = targetRepository.findById(id);
>         assertThat("The inserted row is found in the target repository",
>                    maybeLink.isPresent(),
>                    is(true));
> ```
</details>


This could be reduced/simplified to a comparison that the list of all link IDs in database equals to a singleton of ID extracted from the result object.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java, line 108 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbuGCgj5oFD3Ppdkyor:-MbuGCgj5oFD3Ppdkyos:b5dr9n0) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java#L108)):*
> ```
> NetworkType.ROAD
> ```

What about changing networkType? Should tests cover such a change as well? In real world scenarios that would probably not happen at least very often.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java, line 178 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbuGe8KDuIJWQw_87jD:-MbuGe8KDuIJWQw_87jE:b36222x) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java#L178)):*
> ```
>         assertThat("The target row was not changed",
>                    maybeLink.get().geometry(),
>                    is(LINE_1));
> ```

Ideally, a hashcode calculated over mutable properties would be a more reliable way to ascertain that changes have not occurred to any other properties as well like networkType.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java, line 208 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbuGtoh5cnUbR_79qpI:-MbuGtoh5cnUbR_79qpJ:b-rshvzi) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java#L208)):*
> ```
>         assertThat("Target repository should be empty after import",
>                    targetRepository.empty(),
>                    is(true));
> ```

How can we be sure that delete operation is not accidentally deleting all rows from database? Therefore, I would add a second link into initial dataset to verify that only the row that should be affected is just deleted.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/node/support/NodeImportRepositoryTest.java, line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbtZTxu5OSEXKBSP7-3:-MbtZTxu5OSEXKBSP7-4:b-24a8k4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/test/java/fi/hsl/jore/importer/feature/batch/node/support/NodeImportRepositoryTest.java#L56)):*
> ```
> whenNewStagedRowsAndCommit
> ```

There are actually two NodeImportRepository methods being tested: submitToStaging and commitStagingToTarget. I usually prefer tests which isolate testing to only one method. If the test fails the failure may originate from either method. However, such test philosophy would be too laborous to adopt at this stage.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/point/support/LinkPointImportRepositoryTest.java, line 103 at r1](https:// [...]

2021-06-11 10:18 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12)* status: 51 of 53 files reviewed, 16 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/dto/ImportableLink.java, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbuBIAR9fhb0zsFR3cl:-MbuTYeZEsod7QK_Qy3J:b-wykubk) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/dto/ImportableLink.java#L10)):*
This is actually documented in the commit message:

> - Also, note the difference between ImportableFoo and
>   PersistableFoo:
>   - The former is used with the ImportFooRepositories
>   - The latter is used with the FooRepositories
>   - At the moment they are similar, but later when we
>     add foreign key constrains they will differ

I _could_ add marker interface(s) (`ImportableEntity` and perhaps `PersistableEntity`) and move the documentation there (and perhaps refer to it in `IImportRepository<ENTITY extends ImportableEntity, ...`) but I'm not sure if all that ceremony is necessary.
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/node/dto/ImportableNode.java, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbtWYrcB9WmK7PdKjDt:-MbuULpB-1O4RZ5XZzCm:bpr2e3n) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/main/java/fi/hsl/jore/importer/feature/infrastructure/node/dto/ImportableNode.java#L10)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> CommonFields
> ```

There exists multiple CommonFields interfaces (one for nodes, another for links). This specific CommonFields is for nodes. Still it requires a generic type argument. I would have preferred distinct names like CommonNodeFields and CommonLinkFields. What's your opinion on "overloaded" interface names?
</blockquote></details>

At the moment the type argument is necessary, as it defines the return type of the modifiers (e.g. `T withGeometry(LineString geometry);`). Note that because the `CommonFields<T>` is implemented by several variations of the same base type (e.g. for nodes both `ImportableNode`, `PersistableNode` and `Node`), dropping the type argument would require generating 3 different interfaces just for nodes.

On the other hand, these modifiers are only used as helper methods in tests. They could be replaced by directly copying the underlying instance with something like

```java
// before
final PersistableNode modified = someOtherPersistableNode
     .withGeometry(SOME_GEOMETRY)
     .withFoobar(...)

// after
final PersistableNode modified = ImmutablePersistableNode.copyOf(someOtherPersistableNode)
      .withGeometry(SOME_GEOMETRY)
      .withFoobar(...)
   ...
```

Normally I'd prefer these helper functions (in _production_ code!), because they hide the presence of the concrete `ImmutableSomeClass` -class and allow the user to deal with just the interfaces. However in tests I don't really mind if the tests know about the `ImmutableSomeClass` class.
___
*[src/test/java/fi/hsl/jore/importer/config/jobs/ImportLinksStepTest.java, line 60 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbtYvag0K7Zmn1zAK55:-Mbu_75M5jcqSfCN7-Zi:b-wqt9ps) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f73f704de6ac9e439df48359c912fc9de093e55e/src/test/java/fi/hsl/jore/importer/config/jobs/ImportLinksStepTest.java#L60)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> testUpdatingExistingLink()
> ```

Hmmm...processing got more complex but tests got reduced. But I think it is okay, because here it is essential to test that interaction with database through repository has occurred.
</blockquote></details>

I need to double-check this. It may be possible that something has been dropped during refactoring this commit.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java, line 108 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbuGCgj5oFD3Ppdkyor:-MbuXcsf4TJLP785GO1k:bvz8w8i) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java#L108)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> NetworkType.ROAD
> ```

What about changing networkType? Should tests cover such a change as well? In real world scenarios that would probably not happen at least very often.
</blockquote></details>

NetworkType is part of the link identity (also includes the start node and the end node): changing the NetworkType field would cause the importer to consider the link as a new entity and would delete the old one. 

Regardless, should we have a test for such a situation? Sure, why not. At least it will document what will happen if somehow someone changes the NetworkType in Jore3 for an existing imported link.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java, line 178 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbuGe8KDuIJWQw_87jD:-MbuYYvtC2T-pbKnmSEy:bxn2d2k) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java#L178)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>         assertThat("The target row was not changed",
>                    maybeLink.get().geometry(),
>                    is(LINE_1));
> ```

Ideally, a hashcode calculated over mutable properties would be a more reliable way to ascertain that changes have not occurred to any other properties as well like networkType.
</blockquote></details>

A quick-and-dirty solution might be to create an ad hoc `attributeHashCode()` method, which calculates the hashcode over some subset of fields (e.g. we want to exclude database identifiers, timestamps..). However, I think manually creating such a method would be brittle and a maintenance burden.

Perhaps a better approach would be to create a specific `NodeAttributes` DTO, which encapsulates _only_ the attributes, while the `externalId()`, `pk()`, `systemTime()` fields etal. would be in the wrapping DTO (ie. `PersistableNode`, `ImportableNode`, and `Node`)? That we we could simply compare the `node.attributes()` fields against each other, regardless of the node-type. However, that would add even more classes and ceremony when constructing the instances.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java, line 208 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbuGtoh5cnUbR_79qpI:-MbuZeRy3TKGW0qwIaEA:b-ovwaw7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java#L208)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>         assertThat("Target repository should be empty after import",
>                    targetRepository.empty(),
>                    is(true));
> ```

How can we be sure that delete operation is not accidentally deleting all rows from database? Therefore, I would add a second link into initial dataset to verify that only the row that should be affected is just deleted.
</blockquote></details>

Good idea.


<!-- Sent from Reviewable.io -->

2021-06-11 10:31 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12)* status: 51 of 53 files reviewed, 16 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/node/dto/ImportableNode.java, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbtWYrcB9WmK7PdKjDt:-MbubtbcBW_FVNvUIVLI:bu00hm8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/main/java/fi/hsl/jore/importer/feature/infrastructure/node/dto/ImportableNode.java#L10)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

At the moment the type argument is necessary, as it defines the return type of the modifiers (e.g. `T withGeometry(LineString geometry);`). Note that because the `CommonFields<T>` is implemented by several variations of the same base type (e.g. for nodes both `ImportableNode`, `PersistableNode` and `Node`), dropping the type argument would require generating 3 different interfaces just for nodes.

On the other hand, these modifiers are only used as helper methods in tests. They could be replaced by directly copying the underlying instance with something like

```java
// before
final PersistableNode modified = someOtherPersistableNode
     .withGeometry(SOME_GEOMETRY)
     .withFoobar(...)

// after
final PersistableNode modified = ImmutablePersistableNode.copyOf(someOtherPersistableNode)
      .withGeometry(SOME_GEOMETRY)
      .withFoobar(...)
   ...
```

Normally I'd prefer these helper functions (in _production_ code!), because they hide the presence of the concrete `ImmutableSomeClass` -class and allow the user to deal with just the interfaces. However in tests I don't really mind if the tests know about the `ImmutableSomeClass` class.
</blockquote></details>

Actually, I was wrong. These (or at least one of the methods) are used in the actual production code:

```java

// NodeProcessor.class
...
        return NodeType.STOP == type ?
                node.withProjectedLocation(item.projectedLocation()) :
                node;

```


<!-- Sent from Reviewable.io -->

2021-06-11 11:13 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12)* status: 51 of 53 files reviewed, 16 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/test/java/fi/hsl/jore/importer/feature/batch/point/support/LinkPointImportRepositoryTest.java, line 176 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-Mbu0bLG43XOEfNmjWYc:-MbukO5y8f5Op9STmse9:b-ve9h7z) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/test/java/fi/hsl/jore/importer/feature/batch/point/support/LinkPointImportRepositoryTest.java#L176)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>         assertThat("Target link should have the updated line points",
>                    maybeLink.get().points().get(),
>                    is(LINEPOINTS_2));
> ```

It is not asserted that the first and last point match with geometry property. It should be asserted that there is no contradiction between geometry and points properties. 
</blockquote></details>

Actually, that's not in the scope of this test. Here we submit both the `Link` and the `LinkGeometry` as-is, and the submit+commit logic does not alter them. It's actually the spring batch job `LinkPointProcessor` whose job it is to take the jore3 row and construct the geometries. And which this commit does not actually test :) I have a later commit(s) where I a) detected a problem with the processor and b) fixed it. I think I could backport the tests here and document that they work incorrectly.


<!-- Sent from Reviewable.io -->

2021-06-14 11:55 UTC, jarkkoka reviewed
> https://stackoverflow.com/a/42217872

Thanks for adding that link for sharing information about the issue.

> Reviewed 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-:-Mc9KrLc6ZkEN9DDJKx3:b20hb8z)* status: all files reviewed, 15 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepository.java, line 95 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-Mc96hla-Eu9_FL8HTAu:-Mc96hla-Eu9_FL8HTAv:bq2nq7z) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ae8ac4bb9b9b326c18fde5e997b763b682b71b5b/src/main/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepository.java#L95)):*
> ```
>                                              .whereNotExists(selectOne()
>                                                                      .from(TARGET_TABLE)
>                                                                      .where(TARGET_TABLE.INFRASTRUCTURE_LINK_EXT_ID.eq(STAGING_TABLE.INFRASTRUCTURE_LINK_EXT_ID))))
> ```

This is more conservative and more understandable form IMHO.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/node/support/NodeImportRepository.java, line 96 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbqqxUU5OYXZn5kiuox:-Mc9LDSj57o34qR5hckn:b9oymf2) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/main/java/fi/hsl/jore/importer/feature/batch/node/support/NodeImportRepository.java#L96)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Using `WHERE NOT EXISTS` gives a modest performance boost (up-to 10x performance for the commit step but only ~15% gain overall) but more importantly `ON CONFLICT DO NOTHING` may accidentally hide duplicates in the input data (e.g. multiple route directions for the same route and direction but with overlapping dates!). => I'll update this commit to use `WHERE NOT EXISTS`
</blockquote></details>

I believe PostgreSQL (query optimizer) will quite likely transform WHERE NOT EXISTS constructs into anti-joins.
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/dto/ImportableLink.java, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbuBIAR9fhb0zsFR3cl:-Mc97kQb2OagHmFpUkls:b-pgbun2) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/dto/ImportableLink.java#L10)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

This is actually documented in the commit message:

> - Also, note the difference between ImportableFoo and
>   PersistableFoo:
>   - The former is used with the ImportFooRepositories
>   - The latter is used with the FooRepositories
>   - At the moment they are similar, but later when we
>     add foreign key constrains they will differ

I _could_ add marker interface(s) (`ImportableEntity` and perhaps `PersistableEntity`) and move the documentation there (and perhaps refer to it in `IImportRepository<ENTITY extends ImportableEntity, ...`) but I'm not sure if all that ceremony is necessary.
</blockquote></details>

Ok, did not initially note the commit message. Though I prefer code comments because commit messages tend to be buried in history.
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 129 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-Mc9DPmXEdIWlJ7_xoNY:-Mc9DPmXEdIWlJ7_xoNZ:bonzrvf) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ae8ac4bb9b9b326c18fde5e997b763b682b71b5b/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L129)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     public Optional<Link> findByExternalId(final ExternalId externalId) {
>         return db.selectFrom(LINKS)
>                  .where(LINKS.INFRASTRUCTURE_LINK_EXT_ID.eq(externalId.value()))
>                  .fetchStream()
>                  .map(Link::of)
>                  .findFirst();
>     }
> ```
</details>


Since ExternalId can contain any arbitrary string value I think it might be safer to check here whether the result set contains more than one item and throw exception if that happens.

In V5__init_links.sql file you have a unique index defined as:

CREATE UNIQUE INDEX idx_infrastructure_links_ext_id_type
    ON infrastructure_network.infrastructure_links (infrastructure_link_ext_id, infrastructure_network_type);

I don't know whether this unique index is a bit misleading, but based on it, there might be multiple ExternalIds for different network type values. How do you see this?
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/node/repository/NodeRepository.java, line 110 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-Mc9BiPaCt6ZuNTmBYLr:-Mc9BiPaCt6ZuNTmBYLs:bqnapte) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ae8ac4bb9b9b326c18fde5e997b763b682b71b5b/src/main/java/fi/hsl/jore/importer/feature/infrastructure/node/repository/NodeRepository.java#L110)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     public Optional<Node> findByExternalId(final ExternalId externalId) {
>         return db.selectFrom(NODE)
>                  .where(NODE.INFRASTRUCTURE_NODE_EXT_ID.eq(externalId.value()))
>                  .fetchStream()
>                  .map(Node::of)
>                  .findFirst();
>     }
> ```
</details>


Since ExternalId can contain any arbitrary string value I think it could be safer here to check whether the result set contains more than one item and throw exception if that happens.

In V4__init_nodes.sql file you have a unique index defined as:

CREATE UNIQUE INDEX idx_infrastructure_nodes_ext_id_type
    ON infrastructure_network.infrastructure_nodes (infrastructure_node_ext_id, infrastructure_node_type);

I don't know whether this unique index is a bit misleading, but based on it, there might be multiple ExternalIds for different node type values. How do you see this?
___
*[src/test/java/fi/hsl/jore/importer/config/jobs/ImportLinkPointsStepTest.java, line 50 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-Mc9Dv7xAc2rXE-phBqB:-Mc9Dv7xAc2rXE-phBqC:b-bu9nxc) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ae8ac4bb9b9b326c18fde5e997b763b682b71b5b/src/test/java/fi/hsl/jore/importer/config/jobs/ImportLinkPointsStepTest.java#L50)):*
> ```
>        // FIXME: This is broken due to a bug in LinkPointReader
> ```

Will wait a fix in a subsequent commit.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java, line 208 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-MbuGtoh5cnUbR_79qpI:-Mc9HmmL6SLDQVk-RBA7:b-pyppzl) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/test/java/fi/hsl/jore/importer/feature/batch/link/support/LinkImportRepositoryTest.java#L208)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Good idea.
</blockquote></details>

Well resolved. :+1: 
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/point/support/LinkPointImportRepositoryTest.java, line 176 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-Mbu0bLG43XOEfNmjWYc:-Mc9MYDC0Lt7VV8STknv:b-guzsia) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6e71d1332624a302c75f21c831df5568e07eaa57/src/test/java/fi/hsl/jore/importer/feature/batch/point/support/LinkPointImportRepositoryTest.java#L176)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></s [...]

2021-06-15 06:43 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12)* status: all files reviewed, 15 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 129 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-Mc9DPmXEdIWlJ7_xoNY:-McDONkI8aBF73_bgm6r:b-ncll5g) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ae8ac4bb9b9b326c18fde5e997b763b682b71b5b/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L129)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>     public Optional<Link> findByExternalId(final ExternalId externalId) {
>         return db.selectFrom(LINKS)
>                  .where(LINKS.INFRASTRUCTURE_LINK_EXT_ID.eq(externalId.value()))
>                  .fetchStream()
>                  .map(Link::of)
>                  .findFirst();
>     }
> ```

Since ExternalId can contain any arbitrary string value I think it might be safer to check here whether the result set contains more than one item and throw exception if that happens.

In V5__init_links.sql file you have a unique index defined as:

CREATE UNIQUE INDEX idx_infrastructure_links_ext_id_type
    ON infrastructure_network.infrastructure_links (infrastructure_link_ext_id, infrastructure_network_type);

I don't know whether this unique index is a bit misleading, but based on it, there might be multiple ExternalIds for different network type values. How do you see this?
</blockquote></details>

Good catch! The unique constraints did not make much sense (anymore). At some point I decided to refactor how the `ExternalId` fields are constructed: they should contain all the necessary parts that are required to uniquely identify the original entity.
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/node/repository/NodeRepository.java, line 110 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12#-Mc9BiPaCt6ZuNTmBYLr:-McDOvz-2QupljU3PqUN:bte553o) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ae8ac4bb9b9b326c18fde5e997b763b682b71b5b/src/main/java/fi/hsl/jore/importer/feature/infrastructure/node/repository/NodeRepository.java#L110)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>     public Optional<Node> findByExternalId(final ExternalId externalId) {
>         return db.selectFrom(NODE)
>                  .where(NODE.INFRASTRUCTURE_NODE_EXT_ID.eq(externalId.value()))
>                  .fetchStream()
>                  .map(Node::of)
>                  .findFirst();
>     }
> ```

Since ExternalId can contain any arbitrary string value I think it could be safer here to check whether the result set contains more than one item and throw exception if that happens.

In V4__init_nodes.sql file you have a unique index defined as:

CREATE UNIQUE INDEX idx_infrastructure_nodes_ext_id_type
    ON infrastructure_network.infrastructure_nodes (infrastructure_node_ext_id, infrastructure_node_type);

I don't know whether this unique index is a bit misleading, but based on it, there might be multiple ExternalIds for different node type values. How do you see this?
</blockquote></details>

Same comment as above. Also, I noticed that for some reason I had originally included the`node_type` field in the constraint. I'm not sure what my thought process had been; jore3 defines the node id to be unique so I'm not sure why I originally included the node type in the constraint. In any case, I removed it while cleaning up the indexis.


<!-- Sent from Reviewable.io -->

2021-06-15 08:39 UTC, jarkkoka approved these changes
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/12)* status: all files reviewed, 12 unresolved discussions (waiting on @lassemaatta)



<!-- Sent from Reviewable.io -->

2021-06-15 08:47 UTC, merged