Implement data fetching and persisting (attempt #2)
HSLdevcom/jore4-jore3-importer pull request #2
Opened 2021-03-15 10:43 UTC by lassemaatta

- Processing is organized using spring-batch
- Currently supports reading jore 3 links (& nodes)

2021-03-18 14:03 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 0 of 97 files reviewed, 3 unresolved discussions (waiting on @lassemaatta)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MW4XUrJ4ReBHPwABVOX:-MW4XUrJ4ReBHPwABVOY:b-wb786s) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ea81f41145f2a0f323f7d109fcc74b0d0f9927a1/README.md#L3)):*
> ```Markdown
> # Jore 3 => Jore 4 -importer
> 
> This tool implements a batch job for importing data from a Jore 3 database to a Jore 4 database.
> ```

Suggest adding instructions how to launch batch job.
___
*[src/main/java/fi/hsl/jore/importer/config/jooq/converter/LineStringConverter.java, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MW4aLJy8qOtn2eKjDqj:-MW4aLJy8qOtn2eKjDqk:bwakoyi) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ea81f41145f2a0f323f7d109fcc74b0d0f9927a1/src/main/java/fi/hsl/jore/importer/config/jooq/converter/LineStringConverter.java#L24)):*
> ```Java
>         final WKBReader reader = new WKBReader();
>         try {
>             final Geometry geom = reader.read(WKBReader.hexToBytes(databaseObject.toString()));
> ```

I would like to see a comment here (or elsewhere, maybe README.md) stating what SRID (coordinate system) the input geometries are associated with.
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MW4cZ3uEGisMvXjw6Tr:-MW4cZ3uEGisMvXjw6Ts:bln0wb7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ea81f41145f2a0f323f7d109fcc74b0d0f9927a1/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L34)):*
> ```Java
> 
>         record.setInfrastructureNetworkTypeId(link.networkTypePk().value());
>         record.setInfrastructureLinkGeog(link.geometry());
> ```

Hmmm...I think it should be seen somewhere in what SRID the destination geograhies are associated with. Perhaps this class, PersistableLink or even README.md.


<!-- Sent from Reviewable.io -->

2021-03-19 09:29 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 0 of 100 files reviewed, 4 unresolved discussions (waiting on @jarkkoka)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MW4XUrJ4ReBHPwABVOX:-MW8nYbW0BQzXWX4_5F2:b-so5gu2) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ea81f41145f2a0f323f7d109fcc74b0d0f9927a1/README.md#L3)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Suggest adding instructions how to launch batch job.
</blockquote></details>

I'll implement a HTTP endpoint in a separate commit to trigger (and potentially to check the status of) the batch.
___
*[src/main/java/fi/hsl/jore/importer/config/jooq/converter/LineStringConverter.java, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MW4aLJy8qOtn2eKjDqj:-MW8ni8SDfBG4dQavsz9:bd1c5wy) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ea81f41145f2a0f323f7d109fcc74b0d0f9927a1/src/main/java/fi/hsl/jore/importer/config/jooq/converter/LineStringConverter.java#L24)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I would like to see a comment here (or elsewhere, maybe README.md) stating what SRID (coordinate system) the input geometries are associated with.
</blockquote></details>

The converter now persists the SRID using EWKT/EWKB of the target geometry.
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MW4cZ3uEGisMvXjw6Tr:-MW8nws23bqLcWD0v_lv:b-gy2akh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ea81f41145f2a0f323f7d109fcc74b0d0f9927a1/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L34)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Hmmm...I think it should be seen somewhere in what SRID the destination geograhies are associated with. Perhaps this class, PersistableLink or even README.md.
</blockquote></details>

At the moment no coordinate transformations occur. I added references to the source CRS in the `@JoreColumn` annotation.
___
*[src/main/java/fi/hsl/jore/importer/feature/util/GeometryUtil.java, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MW8oCO09Zl96CrEq0K0:-MW8oCO09Zl96CrEq0K1:b-8sqsoi) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/9251f5fa1c24b6a75f2fff7f29093685f0170226/src/main/java/fi/hsl/jore/importer/feature/util/GeometryUtil.java#L20)):*
> ```Java
>     public static final int SRID_WGS84 = 4326;
> 
>     public static final Set<Integer> SRIDS = HashSet.of(SRID_WGS84);
> ```

My idea was that if we need additional coordinate systems (KKJ2, different destination CRS) we could add them here.


<!-- Sent from Reviewable.io -->

2021-03-19 11:50 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 0 of 100 files reviewed, 5 unresolved discussions (waiting on @jarkkoka)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/link_context/LinkContextRowMapper.java, line 45 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MW9IlVp9c6mAhgn33GG:-MW9IgOk2jMlKx8xLLUJ:bs5tvl5) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/9251f5fa1c24b6a75f2fff7f29093685f0170226/src/main/java/fi/hsl/jore/importer/feature/batch/link_context/LinkContextRowMapper.java#L45)):*
> ```
>                                       rs.getDouble("alku_solomx"),
> ```

Most of this code is actually incorrect. For example, `getDouble(..)` is documented as returning 

>  if the value is SQL NULL, the value returned is 0


<!-- Sent from Reviewable.io -->

2021-04-07 09:33 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 0 of 108 files reviewed, 7 unresolved discussions (waiting on @jarkkoka)

___
*[pom.xml, line 140 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXffHzw9KxsQ43BvB4L:-MXffHzxDFRllTCvz2ZT:btnqk1d) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/pom.xml#L140)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         <dependency>
>             <groupId>org.flywaydb</groupId>
>             <artifactId>flyway-core</artifactId>
>         </dependency>
> ```
</details>


This dependency should not be here, as we should NOT run migrations when starting up.
___
*[src/main/resources/application.properties, line 5 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXffUw-3FWWQjA9U9Li:-MXffUw-3FWWQjA9U9Lj:b-1ckuh5) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/resources/application.properties#L5)):*
> ```
> spring.flyway.url=@destination.db.url@
> spring.flyway.user=@destination.db.username@
> spring.flyway.password=@destination.db.password@
> ```

Same here, these are not needed.


<!-- Sent from Reviewable.io -->

2021-04-07 11:37 UTC, jarkkoka requested changes
> Reviewed 65 of 97 files at r1, 13 of 18 files at r2, 35 of 35 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 106 of 108 files reviewed, 34 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/config/jooq/converter/geometry/GeometryConverter.java, line 25 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXaWqoc02lS5dflB_Ad:-MXaWqoc02lS5dflB_Ae:b-xxw0nn) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/config/jooq/converter/geometry/GeometryConverter.java#L25)):*
> ```Java
>         }
> 
>         final WKBReader reader = new WKBReader();
> ```

WKBReader:in käytöstä voisi kirjoittaa kommentin, että se osaa käsitellä PostGIS:in SRID-tiedon. Sehän on EWKB-juttuja, ja ymmärtääkseni tapahtuu implisiittisesti tässä factaustalla. Nyt varmistin asian lukaisemalla WKBReaderin Javadoc-dokumentaatiota.
___
*[src/main/java/fi/hsl/jore/importer/config/jooq/converter/geometry/GeometryConverter.java, line 29 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXaqBL18QdYmYlLtenW:-MXaqBL221S2fJf2a7h1:bm5o0fq) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/config/jooq/converter/geometry/GeometryConverter.java#L29)):*
> ```Java
>             final Geometry geom = reader.read(WKBReader.hexToBytes(databaseObject.toString()));
> 
>             if (!typeName.equals(geom.getGeometryType())) {
> ```

Thinking whether "equalsIgnoreCase" should be used here.
___
*[src/main/java/fi/hsl/jore/importer/config/properties/DataSourceConfigDto.java, line 21 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbL2TJ-qZr-Bl9F-M_:-MXbL2TJ-qZr-Bl9F-Ma:b-nks5s8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/config/properties/DataSourceConfigDto.java#L21)):*
> ```Java
>     String getPassword();
> 
>     String poolName();
> ```

Other methods start with prefix "get". Should this method do the same as well?
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java, line 22 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbQfKF4_Zzr0zJ7ZXj:-MXbQfKF4_Zzr0zJ7ZXk:b-68jo8f) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java#L22)):*
> ```
> Integer
> ```

Primitive int is semantically more correct return value because a null value is never returned.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java, line 29 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbQRrj4AALP_p-y15K:-MXbQRrj4AALP_p-y15L:b963foc) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java#L29)):*
> ```
> Optional<Integer>
> ```

OptionalInt also exists. Thinking about when one should use Optional<Integer> and when OptionalInt? There does not yet exist a style guide for this project...
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java, line 35 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbRKth0_jfZOzYFp98:-MXbRKth0_jfZOzYFp99:b-4bo80d) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java#L35)):*
> ```
> Double
> ```

Primitive double is semantically more correct return value because a null value is never returned from this method.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java, line 42 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbRV7E0OfvVQ2swTf4:-MXbRV7E0OfvVQ2swTf5:b-o6drmy) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java#L42)):*
> ```
> Optional<Double>
> ```

OptionalDouble also exists. Thinking about when one should use Optional<Double> and when OptionalDouble...
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 60 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXg5UWtC6tNjR_Y1byJ:-MXg5UWu27Y35VSN1zEg:b-23spl3) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L60)):*
> ```Java
>                              .getSQL();
> 
>         final Deque<LinkPK> keys = Lists.newLinkedList();
> ```

It might be a bit challenging to maintain code that deals with different collection interfaces. Guava's Lists class is about java.util compatible interfaces whereas the return value of this method is a Vavr type.
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 68 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXez9NQEXsGqCbqT_74:-MXez9NRAONtYapgDdbO:b-gqqrtw) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L68)):*
> ```
> new LineStringConverter()
> ```

I think only one instance of this type could be created and reused in for-loop iterations.
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 87 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXg4vX69MViEv3eU-_k:-MXg4vX69MViEv3eU-_l:b-wnq7rc) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L87)):*
> ```
> Optional<Link>
> ```

I consider this hybrid return value type to be a bit problematic. You are wrapping Vavr List inside a java.util.Optional instead of Vavr Option.
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/entity/JrLink.java, line 38 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXf-3Cn2Ixlucvil1JQ:-MXf-3Co2RFp06p39VB8:bmsr7ym) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/jore/entity/JrLink.java#L38)):*
> ```
> Integer
> ```

This may never be null => hence, a primitive int would be semantically more correct type. With a primitive, it would immediately be clear to the reader that a null-value is not possible.
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/entity/JrLink.java, line 41 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXf-kGU6w8S8JlDzvRY:-MXf-kGU6w8S8JlDzvRZ:b-adr3zb) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/jore/entity/JrLink.java#L41)):*
> ```
> Optional<Integer>
> ```

Is it a general contract with regard to DTO classes (in this code base) that nullable fields are always wrapped with Optional? Asking because plain Integer (wrapper) type would also indicate that a value could be null. I think we need a general style guide in this project.
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/util/JoreGeometryUtil.java, line 20 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXf4UDD65ujfIP9eUlT:-MXf4UDE6DOvGwQqFvtM:biente9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/i [...]

2021-04-08 10:12 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 91 of 109 files reviewed, 34 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/config/jooq/converter/geometry/GeometryConverter.java, line 25 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXaWqoc02lS5dflB_Ad:-MXk8qoTAkAE2p6PTDkd:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/config/jooq/converter/geometry/GeometryConverter.java#L25)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

WKBReader:in käytöstä voisi kirjoittaa kommentin, että se osaa käsitellä PostGIS:in SRID-tiedon. Sehän on EWKB-juttuja, ja ymmärtääkseni tapahtuu implisiittisesti tässä factaustalla. Nyt varmistin asian lukaisemalla WKBReaderin Javadoc-dokumentaatiota.
</blockquote></details>

Done
___
*[src/main/java/fi/hsl/jore/importer/config/jooq/converter/geometry/GeometryConverter.java, line 29 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXaqBL18QdYmYlLtenW:-MXgA8Wb1iqL1Jr2T8D9:bua2j0k) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/config/jooq/converter/geometry/GeometryConverter.java#L29)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Thinking whether "equalsIgnoreCase" should be used here.
</blockquote></details>

At least for now both the `typeName` and `getGeometryType()` refer eventually to the same `Geometry.TYPE_...` constants (no idea why they're not enums), so `.equals()` should be fine. 
___
*[src/main/java/fi/hsl/jore/importer/config/properties/DataSourceConfigDto.java, line 21 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbL2TJ-qZr-Bl9F-M_:-MXk8sfl6xt5xB-V7rDc:bjv5d3n) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/config/properties/DataSourceConfigDto.java#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Other methods start with prefix "get". Should this method do the same as well?
</blockquote></details>

I actually try to avoid the JavaBean naming convention (`getFoo()`) , so I'll remove the `get` prefixes from here.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java, line 22 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbQfKF4_Zzr0zJ7ZXj:-MXkCcyK1U-oWgH8ZElR:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java#L22)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Integer
> ```

Primitive int is semantically more correct return value because a null value is never returned.
</blockquote></details>

Done
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java, line 29 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbQRrj4AALP_p-y15K:-MXkEpXe4YptejtKeEhT:bao65uo) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java#L29)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Optional<Integer>
> ```

OptionalInt also exists. Thinking about when one should use Optional<Integer> and when OptionalInt? There does not yet exist a style guide for this project...
</blockquote></details>

I've never used the `Optional[primitive]` alternatives to plain `Optional<Object>` so I don't know when they're appropriate. It seems that there's some friction when converting between the two variants and the common opinion seems to be that you should avoid the `Optional[primitive]` classes. 

Also, it seems that some future Java versions (Project Valhalla) will try to add support for e.g. `Optional<int>`, which would most likely deprecate the `Optional[primitive]` classes.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java, line 35 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbRKth0_jfZOzYFp98:-MXkFZ9c7PbzQs8Wg-4T:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java#L35)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Double
> ```

Primitive double is semantically more correct return value because a null value is never returned from this method.
</blockquote></details>

Done
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java, line 42 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbRV7E0OfvVQ2swTf4:-MXkF_-WBbNw4yeh_mlM:b-otilcs) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java#L42)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Optional<Double>
> ```

OptionalDouble also exists. Thinking about when one should use Optional<Double> and when OptionalDouble...
</blockquote></details>

See comment above.
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 60 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXg5UWtC6tNjR_Y1byJ:-MXkGM4f6stpbmNMaDnT:b8l5jyg) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L60)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

It might be a bit challenging to maintain code that deals with different collection interfaces. Guava's Lists class is about java.util compatible interfaces whereas the return value of this method is a Vavr type.
</blockquote></details>

I'm trying to follow the convention that a) if I need a mutable collection inside a function (e.g. collecting items one at a time) I'll use `j.u.l` collections for performance but b) try to return immutable `io.vavr` collections to the caller.

I've used Guava immutable collections previously, but their API is subpar (compared to vavr) when manipulating collections.
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 87 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXg4vX69MViEv3eU-_k:-MXkHDXYCxvBsfv57XzD:b-wltaus) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L87)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Optional<Link>
> ```

I consider this hybrid return value type to be a bit problematic. You are wrapping Vavr List inside a java.util.Optional instead of Vavr Option.
</blockquote></details>

There's no `List` here, it's `Link` :) Also, I'm more familiar with `Optional` rather than `Option` and the former seems to work ok (and vavr provides converter APIs).
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/entity/JrLink.java, line 38 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXf-3Cn2Ixlucvil1JQ:-MXkHZ0u8Psgri0ev5lS:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/jo [...]

2021-04-08 10:13 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 91 of 109 files reviewed, 34 unresolved discussions (waiting on @jarkkoka)

___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 68 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXez9NQEXsGqCbqT_74:-MXky6P7DOkgOE5QzNpe:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L68)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> new LineStringConverter()
> ```

I think only one instance of this type could be created and reused in for-loop iterations.
</blockquote></details>

Done
___
*[src/main/java/fi/hsl/jore/importer/feature/util/GeometryUtil.java, line 23 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXg3Qbv7H0TJvRrKcf4:-MXky2gt-vxQKDcb99pI:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/util/GeometryUtil.java#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>     public static final Map<Integer, GeometryFactory> FACTORIES_BY_SRID =
>             SRIDS.toMap(srid -> Tuple.of(srid, buildFor(srid)));
> ```

Maybe could use Guava's CacheBuilder to build a LoadingCache instead of Map.
</blockquote></details>

Done
___
*[src/main/java/fi/hsl/jore/importer/feature/util/GeometryUtil.java, line 33 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXfzIF-CqStB9dQm-wr:-MXky3tABSXjYoYEGDMy:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/util/GeometryUtil.java#L33)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> final GeometryFactory factory
> ```

I think the call-site (user of this class) is not interested in GeometryFactory instances but SRID references. Hence, I would replace the GeometryFactory parameter with an SRID value (likely an enum). Transformation from SRID to GeometryFactory could be done internally in this class.
</blockquote></details>

Done
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/link/support/TransitTypeToNetworkTypeMapper.java, line 4 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbOvigE4vPcheWxytd:-MXkxx3v40vhEJ5dMw-A:bl4vofv) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/batch/link/support/TransitTypeToNetworkTypeMapper.java#L4)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Maybe "jore" package name should actually be "jore3"?
</blockquote></details>

I think I'll do this after these commit(s) are merged to avoid too many rebase conflicts.
___
*[src/test/java/fi/hsl/jore/importer/config/jooq/converter/geometry/LineStringConverterTest.java, line 18 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXg0HM_Cgsm8HQklb9Z:-MXky5I3BbmI02EuSOr7:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/test/java/fi/hsl/jore/importer/config/jooq/converter/geometry/LineStringConverterTest.java#L18)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>     private static final GeometryFactory WGS84_FACTORY =
>             GeometryUtil.FACTORIES_BY_SRID.get(GeometryUtil.SRID_WGS84).get();
> ```

 I think it would be more practical/understandable if the caller needn't deal with GeometryFactories but instead SRID constants.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-04-09 08:49 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 91 of 109 files reviewed, 35 unresolved discussions (waiting on @jarkkoka)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/link/LinkWriter.java, line 23 at r4](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXpo_ODBLdshumIIaJY:-MXpo_ODBLdshumIIaJZ:b-4olv22) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/02867323380e364084343a8b09162631f23c9438/src/main/java/fi/hsl/jore/importer/feature/batch/link/LinkWriter.java#L23)):*
> ```
> private int counter;
> ```

This counter needs to be reset before each step.


<!-- Sent from Reviewable.io -->

2021-04-12 10:59 UTC, jschummer requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 91 of 109 files reviewed, 41 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[dev_deps.sh, line 1 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXqhEGT9PIZLV5s-4OU:-MXqhEGT9PIZLV5s-4OV:b58e2lx) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/dev_deps.sh#L1)):*
> ```
> #!/usr/bin/env 
> ```
nice :-)
___
*[dev_deps.sh, line 32 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXqhdGhAF1Snzji21s6:-MXqhdGhAF1Snzji21s7:b84gqtw) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/dev_deps.sh#L32)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> if [[ -z ${COMMAND} ]]; then
>   instruct_and_exit
> fi
> if [[ ${COMMAND} == "start" ]]; then
> ```
</details>

Would all those ifs look better as a case-statement?
___
*[dev_deps.sh, line 48 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXqgzbf0gMlT-6EErYg:-MXqgzbf0gMlT-6EErYh:b-6gtchm) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/dev_deps.sh#L48)):*
> ```
> stop
> ```
Doesn't maybe make a difference here, but is there any specific reason you use "stop" here instead of "down"?
___
*[pom.xml, line 140 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXffHzw9KxsQ43BvB4L:-MXqhlbsE1hxZx_n2vuT:b-sxclef) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/pom.xml#L140)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
>         <dependency>
>             <groupId>org.flywaydb</groupId>
>             <artifactId>flyway-core</artifactId>
>         </dependency>
> ```

This dependency should not be here, as we should NOT run migrations when starting up.
</blockquote></details>

Maybe add this info to the code and also mention that somebody else (hasura?) is supposed to add migrations.
___
*[README.md, line 7 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXqi63qCfGHMje9rrMA:-MXqi63qCfGHMje9rrMB:b-3uotmx) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/README.md#L7)):*
> ```Markdown
> ## Triggering the batch job
> 
> At the moment the batch job triggers automatically once the application starts. Later, mechanisms for manually triggering the batch job over e.g. HTTP will be added.
> ```

Could you maybe add a line or two about dev_deps.sh ? Mentioning it exists and should be run is probably enough.

Also would be good to mention how to get it to run locally (or that it's not easily possible at the moment).
___
*[src/main/java/fi/hsl/jore/importer/config/properties/DataSourceConfigDto.java, line 21 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbL2TJ-qZr-Bl9F-M_:-MY3gDF25zugmQb7Tcv7:b5le4sg) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/config/properties/DataSourceConfigDto.java#L21)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I actually try to avoid the JavaBean naming convention (`getFoo()`) , so I'll remove the `get` prefixes from here.
</blockquote></details>

I suppose the jooq DTO magic (property <-> column mapping) works without the "get" too? (Not relevant in this class, but generally speaking.)
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/field/NodeType.java, line 7 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MY3gokT1EwEnIIX5C-7:-MY3gokT1EwEnIIX5C-8:by0xy1x) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/src/main/java/fi/hsl/jore/importer/feature/jore/field/NodeType.java#L7)):*
> ```
>     BUS_STOP('P'),
>     CROSSROADS('X'),
>     MUNICIPAL_BORDER('-'),
> ```
I'd also like to see some "jore3"-reference somewhere (maybe in the package name like Jarkko suggested), because it would help understand that these enum values were not chosen for the Jore4 project :-)

Anyhow, fine for me to leave it like this if you promise really hard to do something about it in another PR.
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/mapping/JoreColumn.java, line 29 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MY4hvrh7059SOoEcXXW:-MY4hvrh7059SOoEcXXX:b5u3hsd) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/src/main/java/fi/hsl/jore/importer/feature/jore/mapping/JoreColumn.java#L29)):*
> ```
> 0
> ```
What does '0' mean, what SRID does it refer to?
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/util/JoreGeometryUtil.java, line 20 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXf4UDD65ujfIP9eUlT:-MY4dwMRAc8QlAhbLFYN:b77muj0) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/jore/util/JoreGeometryUtil.java#L20)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Nope, there is no Z axis there.
</blockquote></details>

Is 0 still the best value to use? Or would it be better to use some Helsinki- / capital area average height constant? (Though 0 might be quite close to the truth...)
___
*[src/main/java/fi/hsl/jore/importer/feature/util/GeometryUtil.java, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MW8oCO09Zl96CrEq0K0:-MY4iQY4CWat1hU3RN4j:b-5lkj2c) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/9251f5fa1c24b6a75f2fff7f29093685f0170226/src/main/java/fi/hsl/jore/importer/feature/util/GeometryUtil.java#L20)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

My idea was that if we need additional coordinate systems (KKJ2, different destination CRS) we could add them here.
</blockquote></details>

Could / should this comment be added to the code too?
___
*[src/main/java/fi/hsl/jore/importer/feature/util/ResourceUtil.java, line 1 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXfzl3jCLLhwOlWLLGo:-MY4eSjj0wzvFPp7mjmf:b-mosqg8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/util/ResourceUtil.java#L1)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

That's true. On the other hand, I have a tendency to create multiple `util` packages in different scopes instead of creating one massive "I didn't know where to put this class so I'll put it in `utils`"-package :)

I think I'll revisit this issue once the next few commits have been reviewed and merged.
</blockquote></details>

With some functionality, I also feel they could be in a more general (upper-level) util package. But don't see it as a blocker for this PR:
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/link/LinkWriter.java, line 23 at r4](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXpo_ODBLdshumIIaJY:-MY3gU9CArda1wbQOuF1:b-mnubjh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/02867323380e364084343a8b09162631f23c9438/src/main/java/fi/hsl/jore/importer/feature/batch/link/LinkWriter.java#L23)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> private int counter;
> ```

This counter needs to be reset before each step.
</blockquote></details>

Not sure what you put this comment here :-) Should this information go as a comment in the code?


<!-- Sent from Reviewable.io -->

2021-04-12 12:03 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 91 of 109 files reviewed, 41 unresolved discussions (waiting on @jarkkoka, @jschummer, and @lassemaatta)

___
*[dev_deps.sh, line 32 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXqhdGhAF1Snzji21s6:-MY4w0_k7wzDHcpJY2eU:b-ne5dco) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/dev_deps.sh#L32)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> if [[ -z ${COMMAND} ]]; then
>   instruct_and_exit
> fi
> if [[ ${COMMAND} == "start" ]]; then
> ```
Would all those ifs look better as a case-statement?
</blockquote></details>

Not really, the bash case statement syntax is horrible :)
___
*[dev_deps.sh, line 48 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXqgzbf0gMlT-6EErYg:-MY4wzPD8nYwfkogXHnR:b6u89vp) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/dev_deps.sh#L48)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> stop
> ```
Doesn't maybe make a difference here, but is there any specific reason you use "stop" here instead of "down"?
</blockquote></details>

Nope. My philosophy with docker is "if it seems to work most of the times -> don't touch it".
___
*[src/main/java/fi/hsl/jore/importer/config/properties/DataSourceConfigDto.java, line 21 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbL2TJ-qZr-Bl9F-M_:-MY4mnb41k_O8ZcaUQcW:bi12han) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/config/properties/DataSourceConfigDto.java#L21)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I suppose the jooq DTO magic (property <-> column mapping) works without the "get" too? (Not relevant in this class, but generally speaking.)
</blockquote></details>

I have no experience with any jOOQ magic regarding DTOs, I try to be rather explicit on how SQL results are mapped to DTOs.
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/field/NodeType.java, line 7 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MY3gokT1EwEnIIX5C-7:-MY4qKRxCKvyzrBLrQ0p:beq93m4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/src/main/java/fi/hsl/jore/importer/feature/jore/field/NodeType.java#L7)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
>     BUS_STOP('P'),
>     CROSSROADS('X'),
>     MUNICIPAL_BORDER('-'),
> ```
I'd also like to see some "jore3"-reference somewhere (maybe in the package name like Jarkko suggested), because it would help understand that these enum values were not chosen for the Jore4 project :-)

Anyhow, fine for me to leave it like this if you promise really hard to do something about it in another PR.
</blockquote></details>

I think I'll rename the package in a later commit, otherwise I fear there will be lots of rebase conflicts.
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/mapping/JoreColumn.java, line 29 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MY4hvrh7059SOoEcXXW:-MY4qTqvEoTcylNDqhTz:b-7ihb8l) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/src/main/java/fi/hsl/jore/importer/feature/jore/mapping/JoreColumn.java#L29)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> 0
> ```
What does '0' mean, what SRID does it refer to?
</blockquote></details>

Nothing. It's just the placeholder value for columns with no SRID. 
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/util/JoreGeometryUtil.java, line 20 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXf4UDD65ujfIP9eUlT:-MY4s-XD17B_e3iokh6w:b-kfmgzr) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/jore/util/JoreGeometryUtil.java#L20)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Is 0 still the best value to use? Or would it be better to use some Helsinki- / capital area average height constant? (Though 0 might be quite close to the truth...)
</blockquote></details>

No idea. I assume the best way would be to take the original KKJ2 coordinates (x and y) and convert them, because I guess the conversion would know the height map of the KKJ2 coordinate system and factor that in into the conversion. But I get very poor accuracy when I try that :(
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/link/LinkWriter.java, line 23 at r4](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXpo_ODBLdshumIIaJY:-MY4pNJk7CXwhYR8n1n-:bb6p55t) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/02867323380e364084343a8b09162631f23c9438/src/main/java/fi/hsl/jore/importer/feature/batch/link/LinkWriter.java#L23)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Not sure what you put this comment here :-) Should this information go as a comment in the code?
</blockquote></details>

This comment was originally made regarding an earlier revision, which I later fixed in a later revision (see `counter = 0;` below). Reviewable doesn't seem to show when a comment was made, ie. does it apply to the latest revision or an earlier one.


<!-- Sent from Reviewable.io -->

2021-04-15 08:40 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 95 of 117 files reviewed, 41 unresolved discussions (waiting on @jarkkoka, @jschummer, and @lassemaatta)

___
*[pom.xml, line 140 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXffHzw9KxsQ43BvB4L:-MYJfeRQ7fId1PqPhRvz:b-mn0qm3) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/pom.xml#L140)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Maybe add this info to the code and also mention that somebody else (hasura?) is supposed to add migrations.
</blockquote></details>

I added these back and clarified that this app runs the migrations only when developing locally (assuming a specific environment variable is set).
___
*[README.md, line 7 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXqi63qCfGHMje9rrMA:-MYJfn1KAv8aeNYS1aO8:bz9j3hw) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/README.md#L7)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Could you maybe add a line or two about dev_deps.sh ? Mentioning it exists and should be run is probably enough.

Also would be good to mention how to get it to run locally (or that it's not easily possible at the moment).
</blockquote></details>

Readme has been updated.


<!-- Sent from Reviewable.io -->

2021-04-19 08:42 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 95 of 117 files reviewed, 41 unresolved discussions (waiting on @jarkkoka, @jschummer, and @lassemaatta)

___
*[dev_deps.sh, line 32 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXqhdGhAF1Snzji21s6:-MYdHbQd5pVnMlktRbV_:byd2xh8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/dev_deps.sh#L32)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Not really, the bash case statement syntax is horrible :)
</blockquote></details>

I don't know, I like my approach at least with the case statement :D https://github.com/HSLdevcom/jore4-deploy/blob/main/development.sh


<!-- Sent from Reviewable.io -->

2021-04-19 12:53 UTC, jschummer reviewed
> Reviewed 5 of 18 files at r4, 1 of 1 files at r5, 1 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 102 of 117 files reviewed, 36 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[dev_deps.sh, line 32 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXqhdGhAF1Snzji21s6:-MYOKGORBp-yLgUfDC94:b-beb191) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/dev_deps.sh#L32)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Not really, the bash case statement syntax is horrible :)
</blockquote></details>

Well, at least it gets rid of the duplicate ` ${COMMAND} ==`  But then again this is nicely readable too, so I don't mind if you want to leave it like this.
___
*[dev_deps.sh, line 48 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXqgzbf0gMlT-6EErYg:-MYOLGyFELnTByiCdEcH:brz865y) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/dev_deps.sh#L48)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Nope. My philosophy with docker is "if it seems to work most of the times -> don't touch it".
</blockquote></details>

In general I prefer slightly more deterministic approaches :-D But I think the `stop` is good here, especially because you use `rm`next, which does part of what `down` would do.
___
*[src/main/java/fi/hsl/jore/importer/config/properties/DataSourceConfigDto.java, line 21 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXbL2TJ-qZr-Bl9F-M_:-MYe80720J8LCvk8YHjV:bjuz6e3) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/config/properties/DataSourceConfigDto.java#L21)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I have no experience with any jOOQ magic regarding DTOs, I try to be rather explicit on how SQL results are mapped to DTOs.
</blockquote></details>

Ok, I for myself like to avoid boilerplate code. But then again I've also had cases when a typo in the DTO property or column name was noticed only when debugging at run-time :-)

So in that sense there's good reasons for using more verbose coding style. (Btw in this case the other way around, mapping the SQL fields from the DTO.)
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/mapping/JoreColumn.java, line 29 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MY4hvrh7059SOoEcXXW:-MYeAeZ7B0a_SjtO1viO:b-fchl29) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/2c1a11d21f436c6a5e1648874c0f0963014a72c8/src/main/java/fi/hsl/jore/importer/feature/jore/mapping/JoreColumn.java#L29)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Nothing. It's just the placeholder value for columns with no SRID. 
</blockquote></details>

Ok, so null is no good here?
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/util/JoreGeometryUtil.java, line 20 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXf4UDD65ujfIP9eUlT:-MYeAx9LD5IKSjAnuovR:b-iez68g) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/jore/util/JoreGeometryUtil.java#L20)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

No idea. I assume the best way would be to take the original KKJ2 coordinates (x and y) and convert them, because I guess the conversion would know the height map of the KKJ2 coordinate system and factor that in into the conversion. But I get very poor accuracy when I try that :(
</blockquote></details>

Ok, could you maybe add a comment in the code about that?


<!-- Sent from Reviewable.io -->

2021-04-20 08:03 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: 102 of 117 files reviewed, 36 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/jore/util/JoreGeometryUtil.java, line 20 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXf4UDD65ujfIP9eUlT:-MYiCOM025DKvnOIaizg:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/jore/util/JoreGeometryUtil.java#L20)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Ok, could you maybe add a comment in the code about that?
</blockquote></details>

Done.
___
*[src/main/java/fi/hsl/jore/importer/feature/util/ResourceUtil.java, line 1 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXfzl3jCLLhwOlWLLGo:-MYiCb1TAr7FGUkMyfHL:b-g0s3ss) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/util/ResourceUtil.java#L1)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

With some functionality, I also feel they could be in a more general (upper-level) util package. But don't see it as a blocker for this PR:
</blockquote></details>

This is fixed in another commit.


<!-- Sent from Reviewable.io -->

2021-04-20 09:30 UTC, jarkkoka approved these changes
> Reviewed 8 of 18 files at r4, 6 of 7 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: all files reviewed, 23 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/config/jooq/converter/geometry/GeometryConverter.java, line 46 at r7](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MYiV0Fv5s2cd_43_gzV:-MYiV0Fv5s2cd_43_gzW:bagoqac) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e4e2601dbf403c85e6dd2487b0d9a1fcc6b4b595/src/main/java/fi/hsl/jore/importer/config/jooq/converter/geometry/GeometryConverter.java#L46)):*
> ```
>         // Note that the WKTWriter does _not_ support the PostGIS EWKT format,
>         // hence we must manually add the SRID prefix
> ```
Good clarification!
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 60 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXg5UWtC6tNjR_Y1byJ:-MYiVino4uDG5rgalKoR:bb0bgs) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L60)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I'm trying to follow the convention that a) if I need a mutable collection inside a function (e.g. collecting items one at a time) I'll use `j.u.l` collections for performance but b) try to return immutable `io.vavr` collections to the caller.

I've used Guava immutable collections previously, but their API is subpar (compared to vavr) when manipulating collections.
</blockquote></details>

Ok, sounds logical.
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 87 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXg4vX69MViEv3eU-_k:-MYiW5mv8FNy3Lnmpo3P:bb9ez1i) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L87)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

There's no `List` here, it's `Link` :) Also, I'm more familiar with `Optional` rather than `Option` and the former seems to work ok (and vavr provides converter APIs).
</blockquote></details>

Ok, my bad. Don't know what I was thinking back then. :) Maybe something about mixing java.util.Optionals and io.vavr.Lists as return value types of methods appearing in one class.
___
*[src/main/java/fi/hsl/jore/importer/feature/jore/entity/JrLink.java, line 41 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXf-kGU6w8S8JlDzvRY:-MYiZUwuDukzQYzMobvY:b-uid6qv) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/jore/entity/JrLink.java#L41)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I've used package-level `@NonNullApi` and `@NonNullFields` annotations to indicate that all return values, arguments etc are `@NonNull` by default. Therefore a plain `Integer foo()` would implicitly be `@NonNull`. Of course this is all just ceremony for the IDE to get warning highlights. 

If I need to indicate that a particular field may be empty, I'll use `Optional` so that the caller must deal with it.

In some special cases I've explicitly added `@Nullable` but mostly when dealing with existing Java API's (e.g. implementing some interface function from a library which can receive null values).
</blockquote></details>

Ok, nice usage of nullable annotations. I wasn't actually aware of these Spring-specific annotations. I think they were introduced in order to make Spring Framework API
null-safe for Kotlin projects. But those are also useful for Java developers when using IntelliJ IDEA which also understands them to generate warnings when unsafe nullable usages are detected.

I also like solutions that force user to not do things wrong. If I correctly understood your aim @Nullable annotation are kind of banned or at least Optionals are preferred over them.


<!-- Sent from Reviewable.io -->

2021-04-20 09:41 UTC, lassemaatta reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: all files reviewed, 23 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/jore/entity/JrLink.java, line 41 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2#-MXf-kGU6w8S8JlDzvRY:-MYic5uZ2IuukuRTaGVr:b-s0wfju) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0af19cdaa062dfb16da4c7ff728de784dd0c3a6a/src/main/java/fi/hsl/jore/importer/feature/jore/entity/JrLink.java#L41)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok, nice usage of nullable annotations. I wasn't actually aware of these Spring-specific annotations. I think they were introduced in order to make Spring Framework API
null-safe for Kotlin projects. But those are also useful for Java developers when using IntelliJ IDEA which also understands them to generate warnings when unsafe nullable usages are detected.

I also like solutions that force user to not do things wrong. If I correctly understood your aim @Nullable annotation are kind of banned or at least Optionals are preferred over them.
</blockquote></details>

Yeah, I only add `@Nullable` when I'm dealing with an API that I can't alter and which might provide `null` values. Otherwise I generally try to use `Optional<T>`.


<!-- Sent from Reviewable.io -->

2021-04-20 10:15 UTC, jschummer approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/2)* status: all files reviewed, 23 unresolved discussions (waiting on @jarkkoka and @lassemaatta)



<!-- Sent from Reviewable.io -->

2021-04-20 10:25 UTC, merged