Process scheduled stop points for transmodel import
HSLdevcom/jore4-jore3-importer pull request #42
Opened 2021-11-01 07:49 UTC by pkainulainen-vincit

- Read the Digiroad stop information from a CSV file which
  is found from the file system.
- Implement a Spring Batch item proecssor which combines
  the stop information imported from Jore 3 and Digiroad,
  and created a new TransmodelScheduledStopPoint object
  which can be inserted into the Jore 4 database.
- Write tests

2021-11-01 09:54 UTC, jschummer approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @jarkkoka, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnPnxhb0q4DdahGMrjn:-MnPnxhb0q4DdahGMrjo:bh58px7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L51)):*
> ```
>         //If we cannot find the corresponding Digiroad stop, we cannot
>         //determine the coordinates of the stop. Thus, we must return null
> ```

This is not quite true I think, the stop coordinates are contained in the Jore3 data.

I guess this should say "If we cannot find the corresponding Digiroad stop, we cannot determine on which link the stop resides." (and digitization direction)


<!-- Sent from Reviewable.io -->

2021-11-01 10:37 UTC, jarkkoka requested changes
> Reviewed 14 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42)* status: 14 of 17 files reviewed, 14 unresolved discussions (waiting on @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnPyW_l5hA2gs-gBZMW:-MnPyW_l5hA2gs-gBZMX:bhxue94) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L35)):*
> ```
>     public ScheduledStopPointExportProcessor(DigiroadStopService digiroadStopService) {
> 
>     public TransmodelScheduledStopPoint process(ExportableScheduledStopPoint jore3Stop) throws Exception {
> ```

Your IDE settings seem to have deviated from the style convention of this project as many `final` keywords are dropped. Are you able to fix your IDE settings?
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnPxj5zDkdIQ-C4d6Tz:-MnPxj5zDkdIQ-C4d6U-:b-32vcaq) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L42)):*
> ```
> error
> ```

Not an error IMO since it is not the app's fault if a piece of data is missing. Fix this to `warn` or maybe even `debug`. If am not mistaken there are more than one thousand stops in Jore3 where ELY number is missing. Hence, pretty many lines will be printed into log.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 49 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnPyrw-7M2_h4-qbSPF:-MnPyrw09TmIus0RIWd4:bx9phk9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L49)):*
> ```
>         String elyNumber = jore3Stop.elyNumber().get();
>         Optional<DigiroadStop> digiroadStopContainer = digiroadStopService.findByElyNumber(elyNumber);
> ```

`final` missing here too.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnPnxhb0q4DdahGMrjn:-MnPz01a1uSXAwuxaI5S:bskzdo) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L51)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
>         //If we cannot find the corresponding Digiroad stop, we cannot
>         //determine the coordinates of the stop. Thus, we must return null
> ```

This is not quite true I think, the stop coordinates are contained in the Jore3 data.

I guess this should say "If we cannot find the corresponding Digiroad stop, we cannot determine on which link the stop resides." (and digitization direction)
</blockquote></details>

I agree partly on what @jschummer said. IMO if we cannot find the corresponding Digiroad stop, then we cannot associate the stop with a link easily by an ELY number. Instead, we need to determine the link by finding the closest Digiroad link using geometry information. However, geometry-based link resolution could involve a separate commit and pull request. In that case the direction of stop on link is resolved using RHS buffering technique (PostGIS ST_Buffer).
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 77 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ-nC8Dld2xuuwRwD4:-MnQ-nC8Dld2xuuwRwD5:b-inx80l) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L77)):*
> ```
> boolean
> ```

`static` qualifier missing
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 81 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ-u7i7w7lgFY6BeXp:-MnQ-u7i7w7lgFY6BeXq:bz1qiqa) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L81)):*
> ```
> String 
> ```

`static` qualifier missing
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java, line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ0KOtBAIUDPMAsfZL:-MnQ0KOtBAIUDPMAsfZM:b6wg2oe) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java#L17)):*
> ```
> externalStopId
> ```

Why not `digiroadStopId`? What `external` means here when the name of interface is `DigiroadStop`? "External to Digiroad" would not be correct.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java, line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ0lOe7r1nA_EN9Wkq:-MnQ0lOe7r1nA_EN9Wkr:b-gpb1iq) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java#L19)):*
> ```
> externalLinkId
> ```

Why not `digiroadLinkId`? What `external` means here when the name of interface is `DigiroadStop`? "External to Digiroad" would not be correct.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ16q84_evXFkQlGBV:-MnQ16q84_evXFkQlGBW:bkva6gi) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java#L21)):*
> ```
> elyNumber
> ```

In Digiroad material, the field is not "ELY number" but more like "nationalId" (`valtak_id`).
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java, line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ1ijQEisJhhy7n0aZ:-MnQ1ijQEisJhhy7n0a_:b-imzvu6) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java#L37)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         if (stop == null) {
>             return Optional.empty();
>         }
>         else {
>             return Optional.of(stop);
>         }
> ```
</details>


This is not idiomatic Java. Replace with:
```

        return Optional.ofNullable(stop);
```
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopFactory.java, line 48 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ2IS301G8nkOmPBU-:-MnQ2IS301G8nkOmPBU0:bamm26j) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopFactory.java#L48)):*
> ```
> String
> ```

`final` keywords missing all around this file (also elsewhere). Shoul [...]

2021-11-01 11:17 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42)* status: 14 of 17 files reviewed, 14 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnPyW_l5hA2gs-gBZMW:-MnQ77i442fybK4kda5K:ba317j7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L35)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>     public ScheduledStopPointExportProcessor(DigiroadStopService digiroadStopService) {
> 
>     public TransmodelScheduledStopPoint process(ExportableScheduledStopPoint jore3Stop) throws Exception {
> ```

Your IDE settings seem to have deviated from the style convention of this project as many `final` keywords are dropped. Are you able to fix your IDE settings?
</blockquote></details>

This is now fixed. 
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnPxj5zDkdIQ-C4d6Tz:-MnQ7A_H03RVyBrqT3DA:b-tidsfl) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L42)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> error
> ```

Not an error IMO since it is not the app's fault if a piece of data is missing. Fix this to `warn` or maybe even `debug`. If am not mistaken there are more than one thousand stops in Jore3 where ELY number is missing. Hence, pretty many lines will be printed into log.
</blockquote></details>

Changed this to debug.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 49 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnPyrw-7M2_h4-qbSPF:-MnQ7IeS8Yw_1yZxHyxj:b-886gsx) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L49)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>         String elyNumber = jore3Stop.elyNumber().get();
>         Optional<DigiroadStop> digiroadStopContainer = digiroadStopService.findByElyNumber(elyNumber);
> ```

`final` missing here too.
</blockquote></details>

Fixed
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnPnxhb0q4DdahGMrjn:-MnQCfUT9qzYwXybnMFb:b-j6yzmc) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L51)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I agree partly on what @jschummer said. IMO if we cannot find the corresponding Digiroad stop, then we cannot associate the stop with a link easily by an ELY number. Instead, we need to determine the link by finding the closest Digiroad link using geometry information. However, geometry-based link resolution could involve a separate commit and pull request. In that case the direction of stop on link is resolved using RHS buffering technique (PostGIS ST_Buffer).
</blockquote></details>

Removed this comment.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 77 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ-nC8Dld2xuuwRwD4:-MnQ7QfU1ZvIqBkJjcCs:b-g9qjur) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L77)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> boolean
> ```

`static` qualifier missing
</blockquote></details>

Added static qualifier
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 81 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ-u7i7w7lgFY6BeXp:-MnQ7T7G64g2LTPEMVzJ:b-g9qjur) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L81)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> String 
> ```

`static` qualifier missing
</blockquote></details>

Added static qualifier
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java, line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ0KOtBAIUDPMAsfZL:-MnQ7wem1Smzk0A0yopk:b-qme9p2) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java#L17)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> externalStopId
> ```

Why not `digiroadStopId`? What `external` means here when the name of interface is `DigiroadStop`? "External to Digiroad" would not be correct.
</blockquote></details>

Renamed to digiroadStopId
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java, line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ0lOe7r1nA_EN9Wkq:-MnQ804uChIzj2b2XrvC:b-u3s3oe) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java#L19)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> externalLinkId
> ```

Why not `digiroadLinkId`? What `external` means here when the name of interface is `DigiroadStop`? "External to Digiroad" would not be correct.
</blockquote></details>

Renamed to digiroadLinkId
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java, line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ16q84_evXFkQlGBV:-MnQ8BeODs2BvxOh1IAF:bhipj77) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> elyNumber
> ```

In Digiroad material, the field is not "ELY number" but more like "nationalId" (`valtak_id`).
</blockquote></details>

Renamed to nationalId
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java, line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ1ijQEisJhhy7n0aZ:-MnQ8iPT5bVNWvu43-5y:b-rd3ewl) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/d539732185c094358a74a6fee34c3178d68365c1/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java#L37)):*
> return Optional.ofNullable(stop);
This is now fixed
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopFactory.java, line 48 at r1](https:// [...]

2021-11-01 11:54 UTC, jarkkoka requested changes
> Reviewed 1 of 17 files at r1, 5 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42)* status: 14 of 17 files reviewed, 17 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java, line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQK2zJ-Q-vQZ8FMZsR:-MnQK2zJ-Q-vQZ8FMZsS:b-e07cq9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java#L21)):*
> ```
> String
> ```

In Digiroad, national ID is numeric (integer, not decimal). I think it should be same here.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java, line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQJpAx7Vt1p3FRDdQH:-MnQJpAyAe73htgHXAHA:b-c59g95) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java#L33)):*
> ```
> String
> ```

In Digiroad it is integer not String.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopService.java, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQK_a34miFpKuTanla:-MnQK_a34miFpKuTanlb:b3h5gl) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopService.java#L20)):*
> ```
> String
> ```

Should be `int`.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessorTest.java, line 41 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQKk6J6rxm8yRhKzaI:-MnQKk6J6rxm8yRhKzaJ:b7oy4pp) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/test/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessorTest.java#L41)):*
> ```
> DigiroadStopService
> ```

With `final`
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessorTest.java, line 64 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQKq6vBpHQtjMRZkh_:-MnQKq6vBpHQtjMRZkha:b80r7i1) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/test/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessorTest.java#L64)):*
> ```
> TransmodelScheduledStopPoint
> ```

With `final`
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessorTest.java, line 114 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQL-o2-ACP1yU5whNQ:-MnQL-o3E9rtmfQQy5SX:bkzon8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/test/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessorTest.java#L114)):*
> ```
>  TransmodelScheduledStopPoint
> ```

`final`'s missing in this file.
___
*[src/test/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopServiceTest.java, line 46 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQL6j_-PTWyKg81XZn:-MnQL6j_-PTWyKg81XZo:b-ok5rm2) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/test/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopServiceTest.java#L46)):*
> ```
> Optional<DigiroadStop>
> ```

`final`'s missing from variable declarations in this file.
___
*[src/test/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopFactoryTest.java, line 140 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQLELpDA1hU0dkScZF:-MnQLELpDA1hU0dkScZG:b-ok5rm2) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/test/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopFactoryTest.java#L140)):*
> ```
> Optional<DigiroadStop>
> ```

`final`'s missing from variable declarations in this file.


<!-- Sent from Reviewable.io -->

2021-11-01 12:45 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42)* status: 8 of 17 files reviewed, 17 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java, line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQK2zJ-Q-vQZ8FMZsR:-MnQWaYJDvM_KPx1JwHv:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> String
> ```

In Digiroad, national ID is numeric (integer, not decimal). I think it should be same here.
</blockquote></details>

This is now fixed.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java, line 33 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQJpAx7Vt1p3FRDdQH:-MnQWWyTC9zRddZqR8VP:be1y2gh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java#L33)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> String
> ```

In Digiroad it is integer not String.
</blockquote></details>

This is now fixed
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopService.java, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQK_a34miFpKuTanla:-MnQWdSq4keDcscZ1c23:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopService.java#L20)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> String
> ```

Should be `int`.
</blockquote></details>

This is now fixed.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessorTest.java, line 41 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQKk6J6rxm8yRhKzaI:-MnQQjalDwHc9qyDh6-7:b-886gsx) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/test/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessorTest.java#L41)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> DigiroadStopService
> ```

With `final`
</blockquote></details>

Fixed
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessorTest.java, line 64 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQKq6vBpHQtjMRZkh_:-MnQQkvfB59P_Kts42_y:b-886gsx) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/test/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessorTest.java#L64)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> TransmodelScheduledStopPoint
> ```

With `final`
</blockquote></details>

Fixed
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessorTest.java, line 114 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQL-o2-ACP1yU5whNQ:-MnQQkHz25yBihlqr9Sj:b-886gsx) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/test/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessorTest.java#L114)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>  TransmodelScheduledStopPoint
> ```

`final`'s missing in this file.
</blockquote></details>

Fixed
___
*[src/test/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopServiceTest.java, line 46 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQL6j_-PTWyKg81XZn:-MnQQmgg9-GA2RBmXRr1:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/test/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopServiceTest.java#L46)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Optional<DigiroadStop>
> ```

`final`'s missing from variable declarations in this file.
</blockquote></details>

Fixed.
___
*[src/test/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopFactoryTest.java, line 140 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQLELpDA1hU0dkScZF:-MnQQoIc1chV-Rxg29cq:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/dbab38e18817b5a2c57174dd380f45f5e2817bc2/src/test/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopFactoryTest.java#L140)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Optional<DigiroadStop>
> ```

`final`'s missing from variable declarations in this file.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-11-01 13:04 UTC, jarkkoka requested changes
> Reviewed 1 of 8 files at r2, 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42)* status: 16 of 17 files reviewed, 14 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java, line 21 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQYtfP0AN_C6RpXFXL:-MnQYtfP0AN_C6RpXFXM:bksx6m8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/79fc8827ed225569cb034c3ae5ccc255f793f694/src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java#L21)):*
> ```
> Integer
> ```

Why is this nullable type? Since, national ID exists for all Digiroad stops, there is no need for nullable type. Actually, the convention within this project has been (designed by Lasse) that integer type are either:
(1) `int` (for non-null integer values
(2) `Optional<Integer>` (for nullable integer values)
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java, line 32 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQaB2xBFOWDpwTzDG5:-MnQaB2xBFOWDpwTzDG6:baaaq15) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/79fc8827ed225569cb034c3ae5ccc255f793f694/src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java#L32)):*
> ```
> Integer
> ```

It is the convention of this project to have either (1) `int` or (2) `Optional<Integer>` as integer parameters. 
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java, line 33 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ_G9q4RPH7UvWhVYi:-MnQ_G9q4RPH7UvWhVYj:bqfv8bf) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/79fc8827ed225569cb034c3ae5ccc255f793f694/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java#L33)):*
> ```
> Integer
> ```

Replace with `int`. It makes no sense to pass a null value because it is guaranteed that a stop will not be found in that case.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopFactory.java, line 118 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ_ezjDfE3jqYXrLNw:-MnQ_ezjDfE3jqYXrLNx:b-60ajqh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/79fc8827ed225569cb034c3ae5ccc255f793f694/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopFactory.java#L118)):*
> ```
> private static Integer parseRequiredInteger(final String fieldName, final String source)
> ```

This is such a general-purpose method that you can consider moving this into a utility class inside `util` package.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopService.java, line 20 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ_qh_2ZHBkIeSIIL3:-MnQ_qh_2ZHBkIeSIIL4:be7lphc) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/79fc8827ed225569cb034c3ae5ccc255f793f694/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopService.java#L20)):*
> ```
> Integer
> ```

Replace with `int` since it makes no sense find a stop for null value because it is known that such stop will not be found.


<!-- Sent from Reviewable.io -->

2021-11-02 06:35 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42)* status: 16 of 17 files reviewed, 14 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java, line 21 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQYtfP0AN_C6RpXFXL:-MnQeTi49CTQYyhJk8WT:bytotfm) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/79fc8827ed225569cb034c3ae5ccc255f793f694/src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Integer
> ```

Why is this nullable type? Since, national ID exists for all Digiroad stops, there is no need for nullable type. Actually, the convention within this project has been (designed by Lasse) that integer type are either:
(1) `int` (for non-null integer values
(2) `Optional<Integer>` (for nullable integer values)
</blockquote></details>

This is now int.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java, line 32 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQaB2xBFOWDpwTzDG5:-MnQeVRi0QKb_ftyNL28:bytotfm) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/79fc8827ed225569cb034c3ae5ccc255f793f694/src/main/java/fi/hsl/jore/importer/feature/digiroad/entity/DigiroadStop.java#L32)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Integer
> ```

It is the convention of this project to have either (1) `int` or (2) `Optional<Integer>` as integer parameters. 
</blockquote></details>

This is now int.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java, line 33 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ_G9q4RPH7UvWhVYi:-MnULvB1BDTRztCBFb-X:bytotfm) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/79fc8827ed225569cb034c3ae5ccc255f793f694/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java#L33)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Integer
> ```

Replace with `int`. It makes no sense to pass a null value because it is guaranteed that a stop will not be found in that case.
</blockquote></details>

This is now int.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopFactory.java, line 118 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ_ezjDfE3jqYXrLNw:-MnULyyb0DSM7kdFgsHn:b-92o6zi) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/79fc8827ed225569cb034c3ae5ccc255f793f694/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopFactory.java#L118)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> private static Integer parseRequiredInteger(final String fieldName, final String source)
> ```

This is such a general-purpose method that you can consider moving this into a utility class inside `util` package.
</blockquote></details>

Moved to the StringParserUtil class.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopService.java, line 20 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnQ_qh_2ZHBkIeSIIL3:-MnQe_Vf6nl1GbYm7xVB:b-m9nmse) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/79fc8827ed225569cb034c3ae5ccc255f793f694/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/DigiroadStopService.java#L20)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Integer
> ```

Replace with `int` since it makes no sense find a stop for null value because it is known that such stop will not be found.
</blockquote></details>

this is now int.


<!-- Sent from Reviewable.io -->

2021-11-02 07:30 UTC, jarkkoka requested changes
> Reviewed 1 of 8 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42)* status: all files reviewed, 5 unresolved discussions (waiting on @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 45 at r4](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnUU1NE1npjC6O4Hzwq:-MnUU1NF0QxmM849BtH9:b-jnr4c1) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a1207f3cdd108977464730701a0cb931e5c47551/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L45)):*
> ```
> Integer
> ```

Unnecessary boxing to nullable `Integer` wrapper type -> Change to primitive `int` that is the actual result type of `Integer.parseInt`.
___
*[src/main/java/fi/hsl/jore/importer/feature/jore3/util/StringParserUtil.java, line 7 at r4](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnUWxoACmzRRf9klA0t:-MnUWxoACmzRRf9klA0u:b-fmstp4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a1207f3cdd108977464730701a0cb931e5c47551/src/main/java/fi/hsl/jore/importer/feature/jore3/util/StringParserUtil.java#L7)):*
> ```
>  StringParserUtil
> ```

Seems good that you extracted these methods here. :+1: 
___
*[src/test/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopServiceTest.java, line 55 at r4](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnUXuoR3fyYB1flnhrs:-MnUXuoR3fyYB1flnhrt:bws12m1) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a1207f3cdd108977464730701a0cb931e5c47551/src/test/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopServiceTest.java#L55)):*
> ```
> external
> ```

digiroad


<!-- Sent from Reviewable.io -->

2021-11-02 07:39 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42)* status: 17 of 19 files reviewed, 5 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 45 at r4](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnUU1NE1npjC6O4Hzwq:-MnUZkjMD1_2sfhnVauD:b-qssebl) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a1207f3cdd108977464730701a0cb931e5c47551/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L45)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Integer
> ```

Unnecessary boxing to nullable `Integer` wrapper type -> Change to primitive `int` that is the actual result type of `Integer.parseInt`.
</blockquote></details>

fixed.
___
*[src/test/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopServiceTest.java, line 55 at r4](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/42#-MnUXuoR3fyYB1flnhrs:-MnU_KHgBnqaXZ2Bn5sL:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a1207f3cdd108977464730701a0cb931e5c47551/src/test/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopServiceTest.java#L55)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> external
> ```

digiroad
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-11-02 07:41 UTC, merged