Replace direction boolean with an enum
HSLdevcom/jore4-jore3-importer pull request #46
Opened 2021-11-02 12:11 UTC by pkainulainen-vincit

Because the datatype of the direction column of the
internal_service_pattern.scheduled_stop_point table
is an "enum", this commit ensures that the scheduled
stop point which can be written to Jore4 database
uses an enum when it describes the direction of the
stop point.

2021-11-03 12:07 UTC, jarkkoka requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/46)* status: all files reviewed, 1 unresolved discussion (waiting on @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/entity/TransmodelScheduledStopPointDirection.java, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/46#-Mn_gCt89thMuxW1CRYb:-Mn_gCt89thMuxW1CRYc:bb26m9k) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/932e1fe5395075ca432ea7573080813a90a425ba/src/main/java/fi/hsl/jore/importer/feature/transmodel/entity/TransmodelScheduledStopPointDirection.java#L10)):*
> ```
> backward
> ```

I think the code convention is that enum constants are always in capital. You might assign lowercase strings as private fields (e.g. `databaseValue`) into enum constants.


<!-- Sent from Reviewable.io -->

2021-11-03 13:09 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/46)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/entity/TransmodelScheduledStopPointDirection.java, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/46#-Mn_gCt89thMuxW1CRYb:-Mn_uXP86IM8OPi9Gxb6:bmeepep) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/932e1fe5395075ca432ea7573080813a90a425ba/src/main/java/fi/hsl/jore/importer/feature/transmodel/entity/TransmodelScheduledStopPointDirection.java#L10)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> backward
> ```

I think the code convention is that enum constants are always in capital. You might assign lowercase strings as private fields (e.g. `databaseValue`) into enum constants.
</blockquote></details>

You are right. I replaced lowercase constants with uppercase constants and added a private field which contains the value which is inserted into the Jore 4 db.


<!-- Sent from Reviewable.io -->

2021-11-05 10:12 UTC, jarkkoka reviewed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/46)* status: all files reviewed, 2 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/entity/TransmodelScheduledStopPointDirection.java, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/46#-Mnj_Gy8BkBv9foVUvR9:-Mnj_Gy8BkBv9foVUvRA:b-uthg48) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3c9f7bf77ff8b288f0ba60c547f0fec48da1d72e/src/main/java/fi/hsl/jore/importer/feature/transmodel/entity/TransmodelScheduledStopPointDirection.java#L20)):*
> ```
> @return
> ```

Maybe not properly annotated? I think there should be some text after the annotation.


<!-- Sent from Reviewable.io -->

2021-11-05 10:43 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/46)* status: all files reviewed, 2 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/entity/TransmodelScheduledStopPointDirection.java, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/46#-Mnj_Gy8BkBv9foVUvR9:-Mnjgaq_3g_IzuG4C3oe:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3c9f7bf77ff8b288f0ba60c547f0fec48da1d72e/src/main/java/fi/hsl/jore/importer/feature/transmodel/entity/TransmodelScheduledStopPointDirection.java#L20)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> @return
> ```

Maybe not properly annotated? I think there should be some text after the annotation.
</blockquote></details>

This is now fixed.


<!-- Sent from Reviewable.io -->

2021-11-05 11:01 UTC, jarkkoka approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschummer and @pallost)



<!-- Sent from Reviewable.io -->

2021-11-05 11:03 UTC, merged