Add new fields to stop points and lines imported to Jore4 database
HSLdevcom/jore4-jore3-importer pull request #57
Opened 2021-12-01 13:35 UTC by pkainulainen-vincit

- Use newer Hasura image.
- Add priority and validity period to scheduled stop points.
- Add external id line.
- Add priority and validity period to lines.
- Fix tests.

2021-12-03 13:30 UTC, jarkkoka requested changes
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57)* status: all files reviewed, 22 unresolved discussions (waiting on @jschummer and @pkainulainen-vincit)

___
*[docker/docker-compose.custom.yml, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mpztl3h8XEP4vNX2-pD:-Mpztl3iCir5yHGVL11D:b-wc9y2n) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/docker/docker-compose.custom.yml#L5)):*
> ```
> image: "hsldevcom/jore4-hasura:main--10254a33107fb72ee5fd2b78d4b76000d8626203"
> ```

I think this file is meant to be added to `.gitignore`. At least, jore4-hasura repo it is like that,
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-MpzuM1o2T_Gi37zGnDz:-MpzuM1o2T_Gi37zGnE-:b9u213x) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L38)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>     private static final LocalDateTime DEFAULT_VALIDITY_START = LocalDateTime.of(
>             LocalDate.of(2020, 1, 1),
>             LocalTime.of(4, 30)
>     );
>     private static final LocalDateTime DEFAULT_VALIDITY_END = LocalDateTime.of(
>             LocalDate.of(2051, 1, 1),
>             LocalTime.of(4, 29, 59)
>     );
> 
> ```
</details>


There should be at least some comments describing these odd clock times. I know the background but it definitely is not obvious to many readers.

There should also be comment that explains why a date for year 2051 is better than simple `null`. At least I am not convinced of the benefits of using arbitrary future datetime as opposed to using `null` value.
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mpzvt1nANgwU7G8Fjsr:-Mpzvt1oBseJ0tt0KJQB:bq2af3d) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L36)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         if (!validityPeriod.hasLowerBound()) {
>             return Optional.empty();
>         }
> 
>         final LocalDate startDay  = determineStartDay(validityPeriod);
>         return Optional.of(LocalDateTime.of(startDay, LocalTime.of(4, 30)));
> ```
</details>


Why not use `Optional` as a functional abstraction as it is intended to be used?

```

return Optional.of(validityPeriod)
        .filter(Range::hasLowerBound)
        .map(ValidityPeriodUtil::determineStartDay)
        .map(startDay -> LocalDateTime.of(startDay, LocalTime.of(4, 30)));
```
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 45 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-MpzvOlI9lGYyhng4n6M:-MpzvOlI9lGYyhng4n6N:b-hf7ffz) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L45)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         if (validityPeriod.lowerBoundType() == BoundType.CLOSED) {
>             return lowerEndPoint;
>         }
>         else {
>             return lowerEndPoint.plusDays(1);
>         }
> ```
</details>


Java language provides a ternary operator with which you can make code much shorter and more expressive:

```

return validityPeriod.lowerBoundType() == BoundType.CLOSED ? lowerEndPoint : lowerEndPoint.plusDays(1);
```
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-RiXW4n1FkmXPteoU:-Mq-RiXW4n1FkmXPteoV:b9vnodf) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L64)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         if (!validityPeriod.hasUpperBound()) {
>             return Optional.empty();
>         }
> 
>         final LocalDate endDay = determineEndDay(validityPeriod);
>         return Optional.of(LocalDateTime.of(endDay, LocalTime.of( 4, 29, 59)));
> ```
</details>


Why not use `Optional` as a functional abstraction as it is intended to be used?

```

        return Optional.of(validityPeriod)
                .filter(Range::hasUpperBound)
                .map(ValidityPeriodUtil::determineEndDay)
                .map(endDay -> LocalDateTime.of(endDay, LocalTime.of( 4, 29, 59)));
```
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 71 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-RqzC9KVS4OI_9w4P:-Mq-RqzC9KVS4OI_9w4Q:b9gjbfl) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L71)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         if (validityPeriod.upperBoundType() == BoundType.CLOSED) {
>             return upperEndPoint.plusDays(1);
>         }
>         else {
>             return upperEndPoint;
>         }
> ```
</details>


Use ternary operator to make code more concise and expressive.
___
*[src/main/resources/export/export_lines.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-S8Pg-thSzwO72TTs:-Mq-S8Pg-thSzwO72TTt:blvdgzx) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/resources/export/export_lines.sql#L2)):*
> ```
>  l.network_line_ext_id AS external_id,
> ```

Why is this exported to Hasura database?
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-SP8K4njkGHqE5EUz:-Mq-SP8K4njkGHqE5EV-:b6nut9o) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java#L24)):*
> ```
> private static final String EXTERNAL_ID = "7863";
> ```

Possibly this should not be exported?
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-Ssz4C4txz_jOn1zA:-Mq-Ssz4C4txz_jOn1zB:bf6z36l) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java#L36)):*
> ```
> LocalTime.of(4, 30)
> ```

This clock time is a start time of operating day. I think this should be moved to `Constants` or similar-named class.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java, line 40 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-SaPK7yVVuf3GRI77:-Mq-SaPK7yVVuf3GRI78:b-u8kna0) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java#L40)):*
> ```
> LocalTime.of(4, 29, 59)
> ```

This clock time is an end time of operating day. I think this should be moved to `Constants` or similar-named class.
___
*[src/test/ [...]

2021-12-06 11:42 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57)* status: 28 of 36 files reviewed, 22 unresolved discussions (waiting on @jarkkoka and @jschummer)

___
*[docker/docker-compose.custom.yml, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mpztl3h8XEP4vNX2-pD:-MqENNID69HkLQzhrdJc:b5rezr) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/docker/docker-compose.custom.yml#L5)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> image: "hsldevcom/jore4-hasura:main--10254a33107fb72ee5fd2b78d4b76000d8626203"
> ```

I think this file is meant to be added to `.gitignore`. At least, jore4-hasura repo it is like that,
</blockquote></details>

This file specifies custom configuration (in this case newer images) which must be used if you want to run the importer. Thus, you cannot add this file to `.gitignore` or you can run the importer (and all tests will fail as well).
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-MpzuM1o2T_Gi37zGnDz:-MqESYGD986HpS1rx87K:bozv4y) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L38)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>     private static final LocalDateTime DEFAULT_VALIDITY_START = LocalDateTime.of(
>             LocalDate.of(2020, 1, 1),
>             LocalTime.of(4, 30)
>     );
>     private static final LocalDateTime DEFAULT_VALIDITY_END = LocalDateTime.of(
>             LocalDate.of(2051, 1, 1),
>             LocalTime.of(4, 29, 59)
>     );
> 
> ```

There should be at least some comments describing these odd clock times. I know the background but it definitely is not obvious to many readers.

There should also be comment that explains why a date for year 2051 is better than simple `null`. At least I am not convinced of the benefits of using arbitrary future datetime as opposed to using `null` value.
</blockquote></details>

Added comment which explains why these weird values are used here.
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mpzvt1nANgwU7G8Fjsr:-MqEPfVb2GamcCCdzmAN:b7f33f7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L36)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>         if (!validityPeriod.hasLowerBound()) {
>             return Optional.empty();
>         }
> 
>         final LocalDate startDay  = determineStartDay(validityPeriod);
>         return Optional.of(LocalDateTime.of(startDay, LocalTime.of(4, 30)));
> ```

Why not use `Optional` as a functional abstraction as it is intended to be used?

```

return Optional.of(validityPeriod)
        .filter(Range::hasLowerBound)
        .map(ValidityPeriodUtil::determineStartDay)
        .map(startDay -> LocalDateTime.of(startDay, LocalTime.of(4, 30)));
```
</blockquote></details>

I think that the old fashioned was is easier to understand than the functional way. 
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 45 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-MpzvOlI9lGYyhng4n6M:-MqEXL2I1_0PSmOyTtMl:bs3gvcy) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L45)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>         if (validityPeriod.lowerBoundType() == BoundType.CLOSED) {
>             return lowerEndPoint;
>         }
>         else {
>             return lowerEndPoint.plusDays(1);
>         }
> ```

Java language provides a ternary operator with which you can make code much shorter and more expressive:

```

return validityPeriod.lowerBoundType() == BoundType.CLOSED ? lowerEndPoint : lowerEndPoint.plusDays(1);
```
</blockquote></details>

I think that this is a matter of preference. I "hate" the ternary operator because I think that it's unreadable but I know that other people "love" it. 
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-RiXW4n1FkmXPteoU:-MqEPtwf8hxSccPki6fs:b7f33f7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L64)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>         if (!validityPeriod.hasUpperBound()) {
>             return Optional.empty();
>         }
> 
>         final LocalDate endDay = determineEndDay(validityPeriod);
>         return Optional.of(LocalDateTime.of(endDay, LocalTime.of( 4, 29, 59)));
> ```

Why not use `Optional` as a functional abstraction as it is intended to be used?

```

        return Optional.of(validityPeriod)
                .filter(Range::hasUpperBound)
                .map(ValidityPeriodUtil::determineEndDay)
                .map(endDay -> LocalDateTime.of(endDay, LocalTime.of( 4, 29, 59)));
```
</blockquote></details>

I think that the old fashioned was is easier to understand than the functional way. 
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 71 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-RqzC9KVS4OI_9w4P:-MqEYCOV7ARE32MfX3cw:bim6cg8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L71)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>         if (validityPeriod.upperBoundType() == BoundType.CLOSED) {
>             return upperEndPoint.plusDays(1);
>         }
>         else {
>             return upperEndPoint;
>         }
> ```

Use ternary operator to make code more concise and expressive.
</blockquote></details>

I think that this is a matter of preference. I "hate" the ternary operator because I think that it's unreadable but I know that other people "love" it. 
___
*[src/main/resources/export/export_lines.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-S8Pg-thSzwO72TTs:-MqEQ0by-aRpgnn1voei:b-yn7x41) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/resources/export/export_lines.sql#L2)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>  l.network_line_ext_id AS external_id,
> ```

Why is this exported to Hasura database?
</blockquote></details>

The `TransmodelLine` doesn't have an `externalId` field => it's not exported to Jore 4 database. This query selects the external id simply because I forgot remove it. That being said, my next commit uses the external id when it updates the transmodel id of a line after its information has been exported to Jore 4.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-SP8K4njkGHqE5EUz:-MqEQlw-5z1QK0MfLRBz:bmuf0fs) ([raw file](https://github.com/hsldevcom/jore4-jore3-impo [...]

2021-12-08 07:08 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57)* status: 27 of 37 files reviewed, 22 unresolved discussions (waiting on @jarkkoka and @jschummer)

___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mpzvt1nANgwU7G8Fjsr:-MqNqNu-6_fs5ukpUyuj:b-y5gujn) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L36)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I think that the old fashioned was is easier to understand than the functional way. 
</blockquote></details>

I fixed this by using your proposed solution.
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 45 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-MpzvOlI9lGYyhng4n6M:-MqNphPm4tK2fq7jm4FE:b-mvc2gq) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L45)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I think that this is a matter of preference. I "hate" the ternary operator because I think that it's unreadable but I know that other people "love" it. 
</blockquote></details>

I replaced the if-else with a ternary operator.
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-RiXW4n1FkmXPteoU:-MqNqJpu-EUWTXEHtIrv:b-y5gujn) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L64)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I think that the old fashioned was is easier to understand than the functional way. 
</blockquote></details>

I fixed this by using your proposed solution.
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 71 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-RqzC9KVS4OI_9w4P:-MqNq1sMA87fYVdUR1Xa:b-mvc2gq) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L71)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I think that this is a matter of preference. I "hate" the ternary operator because I think that it's unreadable but I know that other people "love" it. 
</blockquote></details>

I replaced the if-else with a ternary operator.


<!-- Sent from Reviewable.io -->

2021-12-08 12:59 UTC, jarkkoka reviewed
> Reviewed 9 of 10 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57)* status: all files reviewed, 6 unresolved discussions (waiting on @jschummer and @pkainulainen-vincit)

___
*[docker/docker-compose.custom.yml, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mpztl3h8XEP4vNX2-pD:-MqOYRf-DZzrb7-xhlsw:b20s1z8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/docker/docker-compose.custom.yml#L5)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

This file specifies custom configuration (in this case newer images) which must be used if you want to run the importer. Thus, you cannot add this file to `.gitignore` or you can run the importer (and all tests will fail as well).
</blockquote></details>

I think the database migrations you are referring to that were done to `jore4-hasura:main--10254a33107fb72ee5fd2b78d4b76000d8626203` image has already been carried over to jore4-flux repository. Therefore, I think there is no need to have a custom docker-compose file just because of that image identifier. However, the other stuff below, mainly the database definitions and configuration settings via environment variables may differ from the `e2e` docker-compose bundle available from jore4-flux repository (by executing `./development.sh` script). Hence, this file probably needs to exist in the version control as it does now. So, I will retract my previous comment.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-MpzuM1o2T_Gi37zGnDz:-MqOaPzVDOoXA98paZpw:b-i8rymy) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L38)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

Added comment which explains why these weird values are used here.
</blockquote></details>

Thanks. :+1: 
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 38 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-MqOOpsA2ao-tmrKizty:-MqOOpsB5EQ039JOJHGO:bomr87e) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/1474fd7a7d6bf5d45e8fd8fd1a95901c868ad798/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L38)):*
> ```
> TransmodelConstants.OPERATING_DAY_START_TIME
> ```

As it reads here, one could get an impression that the "operating-day-start-time constant" is universal and related to Transmodel. However, the actual constant value may rather be HSL-specific  and not originate from Transmodel. 
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/TransmodelConstants.java, line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-MqOPinKBA8IEzZglSnL:-MqOPinKBA8IEzZglSnM:b-d948i4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/1474fd7a7d6bf5d45e8fd8fd1a95901c868ad798/src/main/java/fi/hsl/jore/importer/feature/transmodel/TransmodelConstants.java#L9)):*
> ```
> TransmodelConstants 
> ```

Based on the two values contained here, I'd rather name this class `ExportConstants` since these constants may not originate from Transmodel specifications. Just to avoid confusion...
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mpzvt1nANgwU7G8Fjsr:-MqOQDlX4bSyiBl2pLYP:bgcpv8g) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L36)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I fixed this by using your proposed solution.
</blockquote></details>

Readability and understandability are important matters. There are different schools of thought, and it largely comes down to personal preference. I will list some issues with the original code snippet:

- The "functional programming" version of the method has only one exit point which is considered less confusing by many.
- `Optional` is a functional abstraction that has its own API. Introducing `Optional`'s into code but not using the API of the `Optional` class looks pretty weird and clumsy. Why introduce the `Optional` variables or return values in the first place, if the programmer is reluctant to actually use it like it is intended to be used and what seems the most natural or obvious way within functional programming style?
- There is heavy use of **Vavr** library in this Maven project. **Vavr** is a functional library for Java 8+. The decision of using functional programming style has been made months ago within this Maven project.

If you want to turn this Maven project from functional programming style into an old fashioned Java project, I think you should make changes all over the code base in order to have consistent code style. Having a hybrid of functional programming and old fashioned programming style gets pretty inconsistent, ugly and confusing pretty quickly IMO. I'd suggest you keep maintaining the functional style that has already been established in this Maven project. It may involve some paradigm shift but I believe the learning process won't be too unrewarding.
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 71 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-RqzC9KVS4OI_9w4P:-MqOaaBj1U9OOu4bVZoF:b-v5ru9s) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L71)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I replaced the if-else with a ternary operator.
</blockquote></details>

Yes, these are largely a matter of preference. My opinion as a reviewer is that replacing if-else structure consisting of two statements and two method exit points with a single statement and exit point makes the code a bit simpler.
___
*[src/main/resources/export/export_lines.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-S8Pg-thSzwO72TTs:-MqObma89fqQpzzLMHfh:b-8micwq) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/resources/export/export_lines.sql#L2)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

The `TransmodelLine` doesn't have an `externalId` field => it's not exported to Jore 4 database. This query selects the external id simply because I forgot remove it. That being said, my next commit uses the external id when it updates the transmodel id of a line after its information has been exported to Jore 4.
</blockquote></details>

Ok, thanks for clarifying my misunderstanding with regard to exporting `externalId` to Jore4 database.
___
*[src/test/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtilTest.java, line 69 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-Tm1CBSceND523Vgx:-MqOVimY3gQRvmq8Uj12:bsfk0xb) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/test/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtilTest.java#L69)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri K [...]

2021-12-08 13:02 UTC, jarkkoka approved these changes
Some minor code style remarks. Please check them and proceed as you like the best.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-:-MqP7VgYEXNnmjdflzjj:b4sbcjf)* status: all files reviewed, 6 unresolved discussions (waiting on @jschummer and @pkainulainen-vincit)



<!-- Sent from Reviewable.io -->

2021-12-09 06:59 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57)* status: all files reviewed, 6 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 38 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-MqOOpsA2ao-tmrKizty:-MqSxRHl2TEhRshL06d5:bwax4d4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/1474fd7a7d6bf5d45e8fd8fd1a95901c868ad798/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L38)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> TransmodelConstants.OPERATING_DAY_START_TIME
> ```

As it reads here, one could get an impression that the "operating-day-start-time constant" is universal and related to Transmodel. However, the actual constant value may rather be HSL-specific  and not originate from Transmodel. 
</blockquote></details>

I renamed the constant to class to `ExportConstants`.
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/TransmodelConstants.java, line 9 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-MqOPinKBA8IEzZglSnL:-MqSxZ80BEbDp296HdxR:b-qu6n94) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/1474fd7a7d6bf5d45e8fd8fd1a95901c868ad798/src/main/java/fi/hsl/jore/importer/feature/transmodel/TransmodelConstants.java#L9)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> TransmodelConstants 
> ```

Based on the two values contained here, I'd rather name this class `ExportConstants` since these constants may not originate from Transmodel specifications. Just to avoid confusion...
</blockquote></details>

Good point. Done.
___
*[src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mpzvt1nANgwU7G8Fjsr:-MqSxa2Q6O3Rl1MnEwAW:babxiln) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/main/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtil.java#L36)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Readability and understandability are important matters. There are different schools of thought, and it largely comes down to personal preference. I will list some issues with the original code snippet:

- The "functional programming" version of the method has only one exit point which is considered less confusing by many.
- `Optional` is a functional abstraction that has its own API. Introducing `Optional`'s into code but not using the API of the `Optional` class looks pretty weird and clumsy. Why introduce the `Optional` variables or return values in the first place, if the programmer is reluctant to actually use it like it is intended to be used and what seems the most natural or obvious way within functional programming style?
- There is heavy use of **Vavr** library in this Maven project. **Vavr** is a functional library for Java 8+. The decision of using functional programming style has been made months ago within this Maven project.

If you want to turn this Maven project from functional programming style into an old fashioned Java project, I think you should make changes all over the code base in order to have consistent code style. Having a hybrid of functional programming and old fashioned programming style gets pretty inconsistent, ugly and confusing pretty quickly IMO. I'd suggest you keep maintaining the functional style that has already been established in this Maven project. It may involve some paradigm shift but I believe the learning process won't be too unrewarding.
</blockquote></details>

 :+1: 
___
*[src/test/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtilTest.java, line 69 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57#-Mq-Tm1CBSceND523Vgx:-MqSxgrs7V76CXcetyoJ:byvccd5) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a3432cbf173ac22807c3b799d701fbd9d8bae3bc/src/test/java/fi/hsl/jore/importer/feature/transmodel/util/ValidityPeriodUtilTest.java#L69)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I'd prefer importing common and widely-used constants statically. IMO the `TestConstants.` prefix does not add value but only prolongs lines unnecessarily. However, you may style it as you best wish since this is a matter of personal preference.
</blockquote></details>

You are right. The test code now uses static imports when it uses the constants defined by the `TestConstants` class.


<!-- Sent from Reviewable.io -->

2021-12-09 07:19 UTC, jarkkoka approved these changes
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/57)* status: all files reviewed, 2 unresolved discussions (waiting on @jschummer and @pkainulainen-vincit)



<!-- Sent from Reviewable.io -->

2021-12-09 07:24 UTC, merged