Export route geometries to the Jore 4 database
HSLdevcom/jore4-jore3-importer pull request #78
Opened 2022-03-25 05:38 UTC by pkainulainen-vincit

- Read route points and geometries from the importer's database.
- Transform the source information into geojson.
- Get the Digiroad route geometries from the Map Matching API.
- Write the Digiroad route geometries to the Jore 4 database.
- Write tests.

Resolves /HSLdevcom/jore4/issues/617

2022-03-25 06:10 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 0 of 188 files reviewed, 1 unresolved discussion (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

___
*[README.md, line 282 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzgTuF7LLgjvns8YiH:-MyzgTuHA1eFGHcabQL2:b-u93uxn) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/README.md#L282)):*
> ```Markdown
> | jore4.db.password     | JORE4_DB_PASSWORD          | jore4-db-password          | \*\*\*\*                                                                         | Password for the jore4 target                                                  |
> |                       | DIGIROAD_STOPS_CSV_VERSION | digiroad-stops-csv-version | 2022-02-03                                                                       | Version of digiroad stops csv file to be downloaded from Azure blob storage    |
> | jore.importer.migrate | JORE_IMPORTER_MIGRATE      | jore-importer-migrate      | false                                                                            | Should the importer should run its own migrations (for local development only) |
> ```

could you please add a line here as well about the new map.matching.api.url parameter? Asking for a fellow colleague who's about the deploy this microservice for you to Kubernetes ;) Thanks!


<!-- Sent from Reviewable.io -->

2022-03-25 06:38 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 0 of 188 files reviewed, 12 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

___
*[development.sh, line 49 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzhorBBjeuD3T6hzx-:-MyzhorBBjeuD3T6hzx0:b-imowpq) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/development.sh#L49)):*
> ```Shell
> start_all() {
>   download_docker_bundle
>   $DOCKER_COMPOSE_CMD up --build -d importer-jooq-database importer-test-database jore4-mssqltestdb jore4-hasura jore4-testdb jore4-jore3importer jore4-mapmatchingdb jore4-mapmatching
> ```

I see you're taking the brave route and didn't pin the version of jore4-mapmatching in your docker-compose.custom.yml :D
___
*[README.md, line 208 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Myzgo699Xp6Er6Q-mGx:-Myzgo699Xp6Er6Q-mGy:b1wf8sl) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/README.md#L208)):*
> ```Markdown
> 6. Configure the absolute path of the CSV file which contains scheduled stop points exported from Digiroad in the 
>    profile specific configuration file.
> 7. Set the value of the `map.matching.api.url` configuration property to: `http://localhost:3005/api/match/public-transport-route/v1/bus.json`.
> ```

this is fine, but for making it more flexible, it'd be more useful to just store the baseUrl in the configuration
`map.matching.api.baseUrl=http://localhost:3005`
___
*[profiles/ci/config.properties, line 75 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzhYRnAihKlWmfL_D1:-MyzhYRnAihKlWmfL_D2:b-12wmng) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/profiles/ci/config.properties#L75)):*
> ```INI
> 
> # The map matching API URL
> map.matching.api.url=
> ```

I think you could hardcode the http://localhost:3005... value here already, it's not really going to be changing developer-by-developer setups
___
*[profiles/dev/config.properties, line 55 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzhKkLB-V5eLyj-6d5:-MyzhKkLB-V5eLyj-6d6:b-12wmng) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/profiles/dev/config.properties#L55)):*
> ```INI
> 
> # The map matching API URL
> map.matching.api.url=
> ```

I think you could hardcode the http://localhost:3005... value here already, it's not really going to be changing developer-by-developer setups
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RouteGeometryRequestDTO.java, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzjX3wEUEa5ZrgG7RC:-MyzjX3wEUEa5ZrgG7RD:bz2ka4p) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RouteGeometryRequestDTO.java#L12)):*
> ```Java
> public class RouteGeometryRequestDTO {
> 
>     private final String type = "LineString";
> ```

This is actually a generic LineString geojson DTO class, not a mapmatching API-related custom class. Most likely you're going to reuse these in other contexts as well. It might be no use to install a maven package for geojson support, but nevertheless this generic class should be renamed to something like `GeoJsonLineStringDTO` and moved to its own module/package/feature or however you have this repository organized ;)
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/GeometryResponseDTO.java, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Myzl4v5BJs78qkDVZ9g:-Myzl4v5BJs78qkDVZ9h:b-hy0cpi) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/GeometryResponseDTO.java#L9)):*
> ```Java
>  * map matching API.
>  */
> public class GeometryResponseDTO {
> ```

this also looks like a generic geojson LineString implementation to me. Might be smart to have all these grouped together
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/ConstantMapMatchingService.java, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyziZGB98M7zX7ulNfn:-MyziZGB98M7zX7ulNfo:bfwesvo) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/ConstantMapMatchingService.java#L16)):*
> ```Java
>  * method is invoked. 
>  */
> public class ConstantMapMatchingService implements IMapMatchingService {
> ```

name suggestion: `MockMapMatchingService`
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingService.java, line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzlNqfCLnVia_QBcFI:-MyzlNqfCLnVia_QBcFJ:b-a1ebik) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingService.java#L37)):*
> ```Java
>     public MapMatchingResponseDTO sendMapMatchingRequest(final ExportableRouteGeometry routeGeometry,
>                                                          final List<ExportableRoutePoint> routePoints) {
>         LOGGER.debug("Sendi g map matching request for the route direction: {}", routeGeometry.routeDirectionId());
> ```

missing the letter 'n'
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingService.java, line 49 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzlalBDrAPrPAaE3PS:-MyzlalBDrAPrPAaE3PT:b-pld51n) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingService.java#L49)):*
> ```Java
>             final String mapMatchingResponseCode = mapMatchingResponse.getCode();
>             if (!mapMatchingResponseCode.equals("Ok")) {
>                 LOGGER.debug("The map matching response status: {} was returned for the route direction: {}",
> ```

question: wouldn't it be simpler to just do this: 
```
String errorMsg = String.format("...", mapMatchingResponseCode, routeGeometry.routeDirectionId);
LOGGER.debug(errorMsg);
throw new MapMatchingException(errorMsg);
```
instead of duplicating the code? Same for other places within this PR as well.

Or does the LOGGER actually store the additional parameters separately as well and not just execute a String.format within?
___
*[src/main/resources/application.properties, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzmdVI28y_qT_-_Tg9:-MyzmdVI28y_qT_-_TgA:b-2pg6v4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/resources/application.properties#L26)):*
> ```INI
> 
> # The map matching API URL
> map.matching.api.url=@map.matching.api.url@
> ```

it's a good habit to leave an extra \n at the end of the file
___
*[src/main/resources/export/export_route_geometries.sql, line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Myzmkf45jklFSyHXEYa:-Myzmkf45jklFSyHXEYb:b-2pg6v4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/resources/export/export_route_geometries.sql#L17)):*
> ```TSQL
>         ORDER BY rl.network_route_link_order
>     ) links ) network_route_direction_shape
> WHERE network_route_direction_shape IS NOT NULL AND rdo.network_route_transmodel_id IS NOT NULL;
> ```

it's a good habit to leave an extra \n at the end of the file


<!-- Sent from Reviewable.io -->

2022-04-06 11:56 UTC, jarkkoka requested changes
First round of comments. Most essential parts of the PR reviewed. Will continue reviewing later but not guaranteed to give more comments in addition to the ones already written.

> Reviewed 39 of 188 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-:-MzyiXHdE4rEHnHBYvnT:b-w6keg1)* status: 39 of 188 files reviewed, 34 unresolved discussions (waiting on @jschummer, @pallost, and @pkainulainen-vincit)

___
*[pom.xml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy4SoR8KdUaLTxSb7g:-Mzy4SoR8KdUaLTxSb7h:bp73org) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/pom.xml#L23)):*
> ```XML
>         <vavr.version>0.10.3</vavr.version>
>         <immutables.version>2.8.2</immutables.version>
>         <jooq.version>3.15.8</jooq.version>
> ```

This version is newer than what Spring Boot officially supports. But I see that this version is actually only used by jOOQ codegen plugin. Hence, this property name is a bit misleading since actual jOOQ dependencies inherit their version through Spring Boot setup. This could be something like `jooq-codegen-plugin.version`



_Code quote:_
```XML
3.15.8
```
___
*[src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java, line 626 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy70d0Ej9WV8EP1G4g:-Mzy70d0Ej9WV8EP1G4h:blu705h) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java#L626)):*
> ```Java
>         return steps.get("exportRouteGeometriesStep")
>                 .allowStartIfComplete(true)
>                 .<ExportableRouteGeometry, TransmodelRouteGeometry>chunk(1)
> ```

I am not comfortable with naming geometry classes. `ExportableRouteGeometry` and `TransmodelRouteGeometry` are not very descriptive/logical names. One cannot compare two geometries and say that one adheres to (or is more like) Transmodel and another not. Route geometry itself does not have characteristics that would relate it to TM.

Why not use more sensible names like `Jore3RouteGeometry` and `Jore4RouteGeometry`? Or `SourceRouteGeometry` and `MatchedRouteGeometry`? Since the result route is created by map-matching process.



_Code quote:_
```Java
ExportableRouteGeometry, TransmodelRouteGeometry
```
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java, line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy9Nwp51p0RY73LtUo:-Mzy9Nwp51p0RY73LtUp:b-h83uy8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java#L22)):*
> ```Java
> 
> /**
>  * Transforms the information of an exported route geometry into a format
> ```

The comment is incorrect. It has nothing to do with format. It is about mapping geometry from one topology network to another.



_Code quote:_
```Java
into a format
```
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy8sr12dLoVHBCKopC:-Mzy8sr12dLoVHBCKopD:b66b9i3) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java#L26)):*
> ```Java
>  */
> @Component
> public class RouteGeometryExportProcessor implements ItemProcessor<ExportableRouteGeometry, TransmodelRouteGeometry> {
> ```

A class name that does not tell about the real intent.

I would name this something like "MapMatchingProcessor" (simple and concise) or "MapMatchingRouteGeometryProcessor" (more verbose).



_Code quote:_
```Java
RouteGeometryExportProcessor
```
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java, line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyAd7dCy9JSQuu0Os5:-MzyAd7e4gx_X0abBl9i:b93cu88) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java#L51)):*
> ```Java
>         }
> 
>         final MapMatchingResponseDTO mapMatchingResponse = mapMatchingService.sendMapMatchingRequest(routeGeometryInput,
> ```

You must also include the route direction name here for logging/debugging purposes. Although that parameter is optional in the map-matching API it should be provided in order to be able to pinpoint possible map-matching issues.



_Code quote:_
```Java
sendMapMatchingRequest(routeGeometryInput,
```
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java, line 68 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyBMjg1u3GFWm0X9RV:-MzyBMjg1u3GFWm0X9RW:b-k8a2o7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java#L68)):*
> ```Java
> 
>         for (final InfrastructureLinkResponseDTO matchedInfraLink: matchedInfraLinks) {
>             final ExternalLinkRefResponseDTO externalLink = matchedInfraLink.getExternalLinkRef();
> ```

I think the word "response" in class name `ExternalLinkRefResponseDTO` is too much.



_Code quote:_
```Java
ExternalLinkRefResponseDTO
```
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilder.java, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyCK-KBPEZZnNVJBLf:-MzyCK-KBPEZZnNVJBLg:bv3a6tg) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilder.java#L27)):*
> ```Java
> 
>         final MapMatchingRequestDTO request = new MapMatchingRequestDTO();
>         request.setRouteId(routeGeometry.routeDirectionId().toString());
> ```

You must not use UUID here since it is not informational. Use instead external ID of Jore3 route direction. Using external ID like "2167-1-20190304" was my intent when designing the map-matching API. That way log messages of map-matching service can be inspected in case of matching issues.

The UUID is completely nonsense with that respect. Within map-matching, we are not interested in Importer's internal UUID values but the real identities of route directions from the source system (Jore3). Map-matching of problematic route directions can then be re-run independent of Importer (and its database values) by only looking at the log messages of map-matching service (and not needing to delve into Importer's internal database).



_Code quote:_
```Java
routeGeometry.routeDirectionId()
```
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestDTO.java, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyadZ05FBrDasb7HsZ:-MzyadZ05FBrDasb7Hs_:b-8w6kh8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestDTO.java#L11)):*
> ```Java
> public class MapMatchingRequestDTO {
> 
>     private String routeId;
> ```

Rename this to `routeDirectionExtId`.



_Code quote:_
```Java
routeId
```
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RouteGeometryRequestDTO.java, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzjX3wEUEa5ZrgG7RC:-MzyaoQMAD21imXLXpId:bk7j79v) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6 [...]

2022-04-07 12:18 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 39 of 188 files reviewed, 34 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[pom.xml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy4SoR8KdUaLTxSb7g:-N-2uU_G6HWsAVatuv4i:b-v99gm3) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/pom.xml#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This version is newer than what Spring Boot officially supports. But I see that this version is actually only used by jOOQ codegen plugin. Hence, this property name is a bit misleading since actual jOOQ dependencies inherit their version through Spring Boot setup. This could be something like `jooq-codegen-plugin.version`
</blockquote></details>

That version is actually used by both jOOQ codegen project and Spring Boot because you can override the jOOQ version by setting the value of the `jooq.version` property (see: https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html#appendix.dependency-versions.properties). Also, IntelliJ Idea displays the correct jOOQ version when I take look at the external libraries used by the project.
___
*[src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java, line 626 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy70d0Ej9WV8EP1G4g:-N-2vcyk5vsmvG0AsznT:bvpl8vt) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java#L626)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I am not comfortable with naming geometry classes. `ExportableRouteGeometry` and `TransmodelRouteGeometry` are not very descriptive/logical names. One cannot compare two geometries and say that one adheres to (or is more like) Transmodel and another not. Route geometry itself does not have characteristics that would relate it to TM.

Why not use more sensible names like `Jore3RouteGeometry` and `Jore4RouteGeometry`? Or `SourceRouteGeometry` and `MatchedRouteGeometry`? Since the result route is created by map-matching process.
</blockquote></details>

I can rename these interfaces, but this means that I have to rename bunch of other interfaces because it's probably a good idea that immutable interfaces use the same naming model. At the moment, these interfaces follow these rules:

* `Importable*` means that the item can be inserted into importer's own database.
* `Exportable*` means that the information is read from the importer's own database and can be exported to an external system.
* `Transmodel*` means that the information can be inserted into the transmodel data model.

Should I rename these interfaces in this PR or should this be done in a separate PR? I think that it's probably a good idea to rename these, but I don't think that we should probably create a new PR which contains only this change. 
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy8sr12dLoVHBCKopC:-N-2wnVuA3w7ZFtLuAt4:b-r5ios1) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java#L26)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

A class name that does not tell about the real intent.

I would name this something like "MapMatchingProcessor" (simple and concise) or "MapMatchingRouteGeometryProcessor" (more verbose).
</blockquote></details>

Again, I can rename this class, but if I do so, we have to probably rename the other `ItemProcessor` classes as well because at the moment everyone of them uses this naming convention. I suggest that we create a separate PR which contains only this change.


<!-- Sent from Reviewable.io -->

2022-04-07 12:41 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 39 of 188 files reviewed, 34 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/ExternalLinkRefResponseDTO.java, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyeClC5c0UJOGEYHBm:-N-3-ZAx4FCR3Vvi5-Ug:b2bwkzj) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/ExternalLinkRefResponseDTO.java#L8)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You seem to add `Response` word into each DTO class that appears as part of map-matching response. I think "response" words could be taken off sub-DTO classes since many DTO classes could also be used in other situations than as part of a bigger response object.
</blockquote></details>

Removed the word response from the names of sub-DTO classes.
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/RouteResponseDTO.java, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzygc218BlJliI4wuyP:-N-30x-Z9ZdPWhLvLC56:b-7rl0jd) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/RouteResponseDTO.java#L11)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Order this logically next to `weight` field (here is alphabetical order). 
</blockquote></details>

done.
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/ConstantMapMatchingService.java, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyziZGB98M7zX7ulNfn:-N-30N6-0RFtlzGpxUKO:b20y4x6) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/ConstantMapMatchingService.java#L16)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

name suggestion: `MockMapMatchingService`
</blockquote></details>

Nice. Renamed this class.
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingService.java, line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzlNqfCLnVia_QBcFI:-N-30Fso4C2NmRnUrWL0:b-hqsmxu) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingService.java#L37)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

missing the letter 'n'
</blockquote></details>

*facepalm*. Added missing 'n'
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingService.java, line 49 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzlalBDrAPrPAaE3PS:-N-3-nQt2S3OELyfYfK5:b-skv966) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingService.java#L49)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

question: wouldn't it be simpler to just do this: 
```
String errorMsg = String.format("...", mapMatchingResponseCode, routeGeometry.routeDirectionId);
LOGGER.debug(errorMsg);
throw new MapMatchingException(errorMsg);
```
instead of duplicating the code? Same for other places within this PR as well.

Or does the LOGGER actually store the additional parameters separately as well and not just execute a String.format within?
</blockquote></details>

The difference is that `LOGGER.debug()` only constructs the log message when the log level is `DEBUG`. In other words, the `String.format()` isn't invoked in production because production most likely uses the log level `INFO` => faster performance.
___
*[src/main/java/fi/hsl/jore/importer/feature/network/route_point/dto/ExportableRoutePoint.java, line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyhJH55BIWo8jyrSmE:-N-31HlC33kbO9vkgvUh:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/network/route_point/dto/ExportableRoutePoint.java#L29)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

too much indent
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2022-04-08 05:11 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 29 of 188 files reviewed, 34 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RouteGeometryRequestDTO.java, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzjX3wEUEa5ZrgG7RC:-N-6ZI30CZRuwy3xRwe_:bbtcvou) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RouteGeometryRequestDTO.java#L12)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Agree with Tamas' comment. There already exists "geojson-jackson" as a dependency in `pom.xml`. I think you should check whether `org.geojson.LineString` could be used instead of this custom class.
</blockquote></details>

Good points. I Replaced this class with `org.geojson.LineString` as suggested by Jarkko.
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RouteGeometryRequestDTO.java, line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzyb26F4pDmQVKbTH-h:-N-6ZO3o-ZFzFwk5EmzI:buvd79l) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RouteGeometryRequestDTO.java#L15)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Would make more sense to rename this `lng` or `lon` on (`longitude`) and `lat` (or `latitude`). `x` and `y` relate to projected coordinate systems (planar 2D) but in the context of this repository we deal with latitudes and longitudes.

However, I suggest you use external library classes instead of creating custom ones since the GeoJSON classes are already present in the Java classpath.
</blockquote></details>

Fixed this by using the library class as suggested.


<!-- Sent from Reviewable.io -->

2022-04-08 05:36 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 24 of 188 files reviewed, 34 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointLocationRequestDTO.java, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzycTYqAA4IH0osPyuJ:-N-6esMiBJf6eQ2XPH4V:b-aqvpmu) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointLocationRequestDTO.java#L7)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

 I think you should check whether `org.geojson.Point` (geojson-jackson) could be used instead of this custom class.
</blockquote></details>

Replaced this class with `org.geojson.Point`.


<!-- Sent from Reviewable.io -->

2022-04-08 05:37 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 24 of 188 files reviewed, 34 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointLocationRequestDTO.java, line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzydGFpDFDlLrItwoVr:-N-6f8c3E8FZz83W9VyL:bob85mv) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointLocationRequestDTO.java#L25)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

We are not dealing here with x and y coordinates of a projected coordinate system but longitudes and latitudes of a spherical coordinate system (WGS84).
</blockquote></details>

This was fixed by replacing this class with `org.geojson.Point`.


<!-- Sent from Reviewable.io -->

2022-04-08 06:11 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 24 of 188 files reviewed, 34 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[README.md, line 208 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Myzgo699Xp6Er6Q-mGx:-N-6meCu7MZhXGHWUxIQ:b-3sanh6) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/README.md#L208)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is fine, but for making it more flexible, it'd be more useful to just store the baseUrl in the configuration
`map.matching.api.baseUrl=http://localhost:3005`

</blockquote></details>

Good catch. Replaced the full url with base url.
___
*[profiles/dev/config.properties, line 55 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzhKkLB-V5eLyj-6d5:-N-6mrwm1f-fciVujFHM:b1736m7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/profiles/dev/config.properties#L55)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think you could hardcode the http://localhost:3005... value here already, it's not really going to be changing developer-by-developer setups
</blockquote></details>

True. Fixed this.


<!-- Sent from Reviewable.io -->

2022-04-08 06:39 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 21 of 190 files reviewed, 34 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/GeometryResponseDTO.java, line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Myzl4v5BJs78qkDVZ9g:-N-6tL-v28pn6Xn4yT8v:bymj0ad) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/GeometryResponseDTO.java#L9)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You could use `org.geojson.LineString` class instead of this one since map-matching API always returns infrastructure link geometries as GeoJSON LineStrings. I think this class should be removed.
</blockquote></details>

I replaced a custom class with the `org.geojson.LineString` class.


<!-- Sent from Reviewable.io -->

2022-04-08 06:40 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 21 of 190 files reviewed, 34 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[profiles/ci/config.properties, line 75 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzhYRnAihKlWmfL_D1:-N-6tkVvDz0RAc689DLD:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/profiles/ci/config.properties#L75)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think you could hardcode the http://localhost:3005... value here already, it's not really going to be changing developer-by-developer setups
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-08 06:41 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 21 of 190 files reviewed, 34 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java, line 68 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyBMjg1u3GFWm0X9RV:-N-6ttnAAKwBklbIqXbC:b-h1z4ad) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java#L68)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think the word "response" in class name `ExternalLinkRefResponseDTO` is too much.
</blockquote></details>

Removed the word Response.


<!-- Sent from Reviewable.io -->

2022-04-08 06:45 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 21 of 190 files reviewed, 34 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java, line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy9Nwp51p0RY73LtUo:-N-6unHf7V2bj3CHTRKz:b-ywciww) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java#L22)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The comment is incorrect. It has nothing to do with format. It is about mapping geometry from one topology network to another.
</blockquote></details>

Fixed comment.
___
*[src/main/resources/application.properties, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzmdVI28y_qT_-_Tg9:-N-6uOwa-oL2r6NT-Z7M:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/resources/application.properties#L26)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it's a good habit to leave an extra \n at the end of the file
</blockquote></details>

Fixed.
___
*[src/main/resources/export/export_route_geometries.sql, line 17 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Myzmkf45jklFSyHXEYa:-N-6uTOaDSnRUnhthwbM:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/resources/export/export_route_geometries.sql#L17)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it's a good habit to leave an extra \n at the end of the file
</blockquote></details>

Fixed.
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/InfrastructureLinkResponseDTO.java, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyfQRYDyeNlxMleVph:-N-6u8js4Q1oKO4Rhi-d:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/InfrastructureLinkResponseDTO.java#L11)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Order this next to `weight` field as is most logical.
</blockquote></details>

Done.
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/InfrastructureLinkResponseDTO.java, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyfF0M4LddqxiPPOaw:-N-6uACZAFojyG9r88KC:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/InfrastructureLinkResponseDTO.java#L13)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Try `org.geojson.LineString` instead.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2022-04-08 06:56 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 20 of 190 files reviewed, 34 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java, line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyAd7dCy9JSQuu0Os5:-N-6wUsX422MHmEUYjqy:b-ky2zrr) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java#L51)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You must also include the route direction name here for logging/debugging purposes. Although that parameter is optional in the map-matching API it should be provided in order to be able to pinpoint possible map-matching issues.
</blockquote></details>

I had no idea that you can pass the route direction name as a parameter because it's not included in the API documentation (https://github.com/HSLdevcom/jore4-map-matching#map-matching-api---for-public-transport-routes). Also, when I took a look at the request DTO (https://github.com/HSLdevcom/jore4-map-matching/blob/main/spring-boot/src/main/kotlin/fi/hsl/jore4/mapmatching/api/PublicTransportRouteMatchRequestDTO.kt), it doesn't have the route direction name parameter either. Should I include the route direction into the route direction id?


<!-- Sent from Reviewable.io -->

2022-04-08 07:04 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 20 of 190 files reviewed, 34 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestDTO.java, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyadZ05FBrDasb7HsZ:-N-6y_6p3Wdzj18DZuhY:baq2qe) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestDTO.java#L11)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Rename this to `routeDirectionExtId`.
</blockquote></details>

It seems that the map matching API expects that the name of this property is `routeId` (see: https://github.com/HSLdevcom/jore4-map-matching#map-matching-api---for-public-transport-routes). Should I rename this field and reconfigure the property name added to the json request body by using the `@JsonProperty` annotation?


<!-- Sent from Reviewable.io -->

2022-04-08 07:16 UTC, jarkkoka reviewed
> Reviewed 2 of 11 files at r2, 3 of 8 files at r3, 1 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 26 of 190 files reviewed, 22 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[pom.xml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy4SoR8KdUaLTxSb7g:-N-6x4Nw6Wl_ZoteyomT:b-yfioo4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/pom.xml#L23)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

That version is actually used by both jOOQ codegen project and Spring Boot because you can override the jOOQ version by setting the value of the `jooq.version` property (see: https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html#appendix.dependency-versions.properties). Also, IntelliJ Idea displays the correct jOOQ version when I take look at the external libraries used by the project.
</blockquote></details>

Ok. Thanks for correcting me!
___
*[src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java, line 626 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy70d0Ej9WV8EP1G4g:-N-6yEv90lmmYGQm7au6:b-9u5kyb) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java#L626)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I can rename these interfaces, but this means that I have to rename bunch of other interfaces because it's probably a good idea that immutable interfaces use the same naming model. At the moment, these interfaces follow these rules:

* `Importable*` means that the item can be inserted into importer's own database.
* `Exportable*` means that the information is read from the importer's own database and can be exported to an external system.
* `Transmodel*` means that the information can be inserted into the transmodel data model.

Should I rename these interfaces in this PR or should this be done in a separate PR? I think that it's probably a good idea to rename these, but I don't think that we should probably create a new PR which contains only this change. 
</blockquote></details>

Ok. Good clarification with regard to naming and perhaps this should be included in README unless it is already there.

I don't think you should rename all the other interfaces since geometries of routes are treated differently since the route geometry itself in the Importer's own database cannot be exported to Jore4.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy8sr12dLoVHBCKopC:-N-6yz1EA7AOSPid5rTX:be5rapt) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java#L26)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

Again, I can rename this class, but if I do so, we have to probably rename the other `ItemProcessor` classes as well because at the moment everyone of them uses this naming convention. I suggest that we create a separate PR which contains only this change.
</blockquote></details>

I don't think you should necessarily rename all the other interfaces. Or would you like to elaborate it a little bit more why?
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java, line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyAd7dCy9JSQuu0Os5:-N-6znmiDqD6B77yAIM9:bp393l5) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java#L51)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I had no idea that you can pass the route direction name as a parameter because it's not included in the API documentation (https://github.com/HSLdevcom/jore4-map-matching#map-matching-api---for-public-transport-routes). Also, when I took a look at the request DTO (https://github.com/HSLdevcom/jore4-map-matching/blob/main/spring-boot/src/main/kotlin/fi/hsl/jore4/mapmatching/api/PublicTransportRouteMatchRequestDTO.kt), it doesn't have the route direction name parameter either. Should I include the route direction into the route direction id?
</blockquote></details>

Yeah. I admit it its poorly documented at the moment and there might be a bad example in the README. You should really use `network_route_direction_ext_id` as `routeId` in map-matching requests since we want to identify unambiguously for which route directions map-matching fails. You know, Jore3's route direction is the entity that owns a geometry.
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestDTO.java, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyadZ05FBrDasb7HsZ:-N-7-zUJ3DxBW6f3KFat:befhbp4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestDTO.java#L11)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

It seems that the map matching API expects that the name of this property is `routeId` (see: https://github.com/HSLdevcom/jore4-map-matching#map-matching-api---for-public-transport-routes). Should I rename this field and reconfigure the property name added to the json request body by using the `@JsonProperty` annotation?
</blockquote></details>

Sorry, my mistake. What I really meant is that you should use `network.network_route_directions.network_route_direction_ext_id` from Importer's database as the value of `routeId` property in map-matching requests. Of course, this cannot be renamed since otherwise requests would be in incorrect form.


<!-- Sent from Reviewable.io -->

2022-04-08 07:25 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 26 of 190 files reviewed, 22 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointRequestDTO.java, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzydWQ40IMA588YhPdV:-N-70BSBAVFC2srMA-f5:b-uptwk0) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointRequestDTO.java#L12)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Change this to `Integer` as it is in the map-matching API. All valid national IDs of public transport stops are integers.
</blockquote></details>

The reason why this is a `String` is that the type of the `elynumero` column of the `jr_pysakki` (Jore 3 DB)  table is `varchar(10)`.  I am not sure if this is caused by bad DB design, but because the source column can contain non numeric data, the type of the  `scheduled_stop_point_ely_number`  column of the `network.scheduled_stop_points` table (importer DB) must be `character varying(10)`.  I can naturally transform the `String` as `Integer` in the `MapMatchingRequestBuillder`class but just wanted to point out that the data model does allow non numeric characters which can lead into problems later. 

Should I make the required changes or can we leave this as is?


<!-- Sent from Reviewable.io -->

2022-04-08 07:38 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 26 of 190 files reviewed, 22 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingService.java, line 49 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzlalBDrAPrPAaE3PS:-N-74zAi47fIyzOcQVZW:b6ksooi) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingService.java#L49)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

The difference is that `LOGGER.debug()` only constructs the log message when the log level is `DEBUG`. In other words, the `String.format()` isn't invoked in production because production most likely uses the log level `INFO` => faster performance.
</blockquote></details>

Actually. Now that I took a fresh look at this, i have to admit that your suggestion makes sense. I fixed this by following your advice.
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingService.java, line 65 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyhERC49rBNNbyVGMA:-N-75XXQECXVlwFJQ0yM:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingService.java#L65)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Duplicated error message also here.
</blockquote></details>

This is now fixed.


<!-- Sent from Reviewable.io -->

2022-04-08 11:45 UTC, jarkkoka reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 27 of 190 files reviewed, 21 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointRequestDTO.java, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzydWQ40IMA588YhPdV:-N-7vn1x8GRIHOmWnCJI:b7zglvc) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointRequestDTO.java#L12)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

The reason why this is a `String` is that the type of the `elynumero` column of the `jr_pysakki` (Jore 3 DB)  table is `varchar(10)`.  I am not sure if this is caused by bad DB design, but because the source column can contain non numeric data, the type of the  `scheduled_stop_point_ely_number`  column of the `network.scheduled_stop_points` table (importer DB) must be `character varying(10)`.  I can naturally transform the `String` as `Integer` in the `MapMatchingRequestBuillder`class but just wanted to point out that the data model does allow non numeric characters which can lead into problems later. 

Should I make the required changes or can we leave this as is?
</blockquote></details>

Yes, I'm aware that ELY number is incorrectly modelled as String in Importer's database (as it is in Jore3 schema). You know, in Digiroad all stop national IDs (ELY numbers) are integers. Map-matching service adheres to the Digiroad modeling of national ID.

In addition, I have not encountered a single scheduled stop point in Jore3 whose ELY number is not a number in case of non-empty/null values. If an ELY number in Jore3 were not a number then for sure there couldn't be found any match for it within Digiroad public transport stops (or their national IDs).

I think a  proper fix would be to change Importer's database schema but an easier fix for now is to set the national ID property null in map-matching request in case an ELY number value cannot be converted to an integer.


<!-- Sent from Reviewable.io -->

2022-04-08 12:13 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 25 of 190 files reviewed, 21 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java, line 51 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyAd7dCy9JSQuu0Os5:-N-84XziCkTI2Pw6UjML:bukd7sl) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java#L51)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Yeah. I admit it its poorly documented at the moment and there might be a bad example in the README. You should really use `network_route_direction_ext_id` as `routeId` in map-matching requests since we want to identify unambiguously for which route directions map-matching fails. You know, Jore3's route direction is the entity that owns a geometry.
</blockquote></details>

This is now fixed (`routeId` contains the route direction ext id, not the UUID).
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilder.java, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyCK-KBPEZZnNVJBLf:-N-84f784FUYCsPkiqXU:b-6u2qp7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilder.java#L27)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You must not use UUID here since it is not informational. Use instead external ID of Jore3 route direction. Using external ID like "2167-1-20190304" was my intent when designing the map-matching API. That way log messages of map-matching service can be inspected in case of matching issues.

The UUID is completely nonsense with that respect. Within map-matching, we are not interested in Importer's internal UUID values but the real identities of route directions from the source system (Jore3). Map-matching of problematic route directions can then be re-run independent of Importer (and its database values) by only looking at the log messages of map-matching service (and not needing to delve into Importer's internal database).
</blockquote></details>

I replaced the UUID with the route direction ext id.
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestDTO.java, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyadZ05FBrDasb7HsZ:-N-84jBWDEAxuoi3Z8_g:b-af482t) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestDTO.java#L11)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Sorry, my mistake. What I really meant is that you should use `network.network_route_directions.network_route_direction_ext_id` from Importer's database as the value of `routeId` property in map-matching requests. Of course, this cannot be renamed since otherwise requests would be in incorrect form.
</blockquote></details>

No problem. This is now fixed and this field contains the external id of the route.


<!-- Sent from Reviewable.io -->

2022-04-08 12:22 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 25 of 190 files reviewed, 21 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointRequestDTO.java, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzydWQ40IMA588YhPdV:-N-86kKtBgtUX0R-CqC7:b-9klctw) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointRequestDTO.java#L12)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Yes, I'm aware that ELY number is incorrectly modelled as String in Importer's database (as it is in Jore3 schema). You know, in Digiroad all stop national IDs (ELY numbers) are integers. Map-matching service adheres to the Digiroad modeling of national ID.

In addition, I have not encountered a single scheduled stop point in Jore3 whose ELY number is not a number in case of non-empty/null values. If an ELY number in Jore3 were not a number then for sure there couldn't be found any match for it within Digiroad public transport stops (or their national IDs).

I think a  proper fix would be to change Importer's database schema but an easier fix for now is to set the national ID property null in map-matching request in case an ELY number value cannot be converted to an integer.

</blockquote></details>

I will change the type of this field to Integer for the time being. I also created a new issue on the project backlog so that this is fixed in a proper way (see: https://github.com/HSLdevcom/jore4/issues/722).


<!-- Sent from Reviewable.io -->

2022-04-10 06:25 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 25 of 190 files reviewed, 21 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointRequestDTO.java, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzydWQ40IMA588YhPdV:-N-H8V7qAHdGsxzVp0vD:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointRequestDTO.java#L12)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I will change the type of this field to Integer for the time being. I also created a new issue on the project backlog so that this is fixed in a proper way (see: https://github.com/HSLdevcom/jore4/issues/722).
</blockquote></details>

This is now fixed.


<!-- Sent from Reviewable.io -->

2022-04-10 06:41 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 24 of 190 files reviewed, 21 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java, line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy8sr12dLoVHBCKopC:-N-HARRg3tiucLGlAsN8:b-itmo85) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportProcessor.java#L26)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I don't think you should necessarily rename all the other interfaces. Or would you like to elaborate it a little bit more why?
</blockquote></details>

I gave this some thought and I agree that it's not necessary to rename the other classes. I renamed this class to `MapMatchingProcessor` as you suggested.


<!-- Sent from Reviewable.io -->

2022-04-10 06:57 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 23 of 190 files reviewed, 21 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointType.java, line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzydzoi6nJK7qHQ4Q7-:-N-HFgUv9Pteo6znC3Uo:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointType.java#L32)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

There may exist municipality border type route points in Jore3. You should transform them to `OTHER` instead of throwing an exception.
</blockquote></details>

This is now fixed.


<!-- Sent from Reviewable.io -->

2022-04-10 06:58 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 23 of 190 files reviewed, 21 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/network/route_point/dto/ExportableRouteGeometry.java, line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyD1-z55lCGntnBaJb:-N-HFrMl2UPwf3dNYgg7:b-2fd6s5) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/network/route_point/dto/ExportableRouteGeometry.java#L19)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You should replace this with the external ID of route direction or add separate field for it.

Using external ID (like "2167-1-20190304") was my intent when designing the map-matching API. That way map-matching logs can be inspected in case of matching problems.
</blockquote></details>

Added the field `routeDirectionExtId`. Also, the external id is send to the map matching api instead of the internal UUID.


<!-- Sent from Reviewable.io -->

2022-04-10 07:19 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 23 of 190 files reviewed, 21 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java, line 626 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-Mzy70d0Ej9WV8EP1G4g:-N-HKeai1V89iyGm1ubV:bb7yojy) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java#L626)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok. Good clarification with regard to naming and perhaps this should be included in README unless it is already there.

I don't think you should rename all the other interfaces since geometries of routes are treated differently since the route geometry itself in the Importer's own database cannot be exported to Jore4.
</blockquote></details>

I gave this some thought and I realized that it's  probably a good idea to take a closer look at these names. Thus, I created a new issue: https://github.com/HSLdevcom/jore4/issues/724


<!-- Sent from Reviewable.io -->

2022-04-10 08:11 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 22 of 190 files reviewed, 21 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/InfrastructureLinkResponseDTO.java, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyfZoQ-epfIgJrRcwj:-N-HWqaFEzwQ7EyUpzY1:b-xlwgcz) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/InfrastructureLinkResponseDTO.java#L14)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

This is actually an ID only existing within map-matching service. It has no meaning outside of map-matching service. Maybe this fact could be reflected in the property name.
</blockquote></details>

I renamed this property.


<!-- Sent from Reviewable.io -->

2022-04-11 04:46 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 22 of 190 files reviewed, 21 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[README.md, line 282 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzgTuF7LLgjvns8YiH:-N-LwN3r45Mtf9QpMSwo:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/README.md#L282)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you please add a line here as well about the new map.matching.api.url parameter? Asking for a fellow colleague who's about the deploy this microservice for you to Kubernetes ;) Thanks!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-11 06:43 UTC, pkainulainen-vincit reviewed
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 20 of 191 files reviewed, 21 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/MapMatchingResponseDTO.java, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MzyftH50b7F5rUkaBEE:-N-MMEuWB6gS1yfCq50E:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/response/MapMatchingResponseDTO.java#L12)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

There are two kinds of map-matching responses. Ones with "Ok" code and list of matched routes (`List<RouteResponseDTO>`). And another ones with a code different from "Ok" equipped with an error message (`String`). You should support both types of responses since not all Jore3 routes can be map-matched to Jore4 infrastructure network.
</blockquote></details>

This is now fixed.


<!-- Sent from Reviewable.io -->

2022-04-11 10:59 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 20 of 191 files reviewed, 12 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

___
*[README.md, line 282 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzgTuF7LLgjvns8YiH:-N-NF_dA9wcTiI5O_Pgu:bbeyb3s) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/README.md#L282)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the environment variable here is probably `MAP_MATCHING_API_BASEURL` and the secret is `map-matching-api-baseurl`
___
*[profiles/ci/config.properties, line 75 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-MyzhYRnAihKlWmfL_D1:-N-NFqnKDeAQPEFjWMyS:b-54bfpb) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/3e9cfd0c704ae23eda104e6abb09ce29c0f5d7c8/profiles/ci/config.properties#L75)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it hardcoded...?


<!-- Sent from Reviewable.io -->

2022-04-11 11:57 UTC, jarkkoka requested changes
> Reviewed 140 of 188 files at r1, 2 of 8 files at r3, 6 of 12 files at r4, 5 of 8 files at r7, 3 of 4 files at r8, 1 of 3 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, 1 of 2 files at r12, 8 of 9 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: all files reviewed, 20 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilder.java, line 63 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NHbyL5VGY1FzJT7Tq:-N-NHbyL5VGY1FzJT7Tr:b1natpr) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilder.java#L63)):*
> ```Java
> 
>             final Point projectedLocation = pointToLocation(input.projectedLocation().orElse(null));
>             routePoint.setProjectedLocation(projectedLocation);
> ```

`nationalId`, `passengerId` and `projectedLocation` are only allowed in case of route stop point (`passengerId` being mandatory). This seems to work but I think it could be more thoughtful to set those properties only if RoutePointType means a stop point.



_Code quote:_
```Java
            routePoint.setNationalId(parseToNationalId(input.stopPointElyNumber()));
            routePoint.setPassengerId(input.stopPointShortId().orElse(null));

            final Point location = pointToLocation(input.location());
            routePoint.setLocation(location);

            final Point projectedLocation = pointToLocation(input.projectedLocation().orElse(null));
            routePoint.setProjectedLocation(projectedLocation);
```
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilder.java, line 85 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NGwGtCnaPH0wPDvsC:-N-NGwGtCnaPH0wPDvsD:b-8bm6l4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilder.java#L85)):*
> ```Java
>     }
> 
>     private static Point pointToLocation(final org.locationtech.jts.geom.Point input) {
> ```

`toGeoJson` would better describe IMHO what this method does. Since both the input and output type is `Point`.



_Code quote:_
```Java
pointToLocation
```
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointRequestDTO.java, line 16 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NIQjc84STiGYgVVcz:-N-NIQjc84STiGYgVVd-:b-tga0qp) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointRequestDTO.java#L16)):*
> ```Java
>     private String passengerId;
>     private Point projectedLocation;
>     private RoutePointType type;
> ```

The ordering of properties is now alphabetical.

The more logical order would be:

1. type  (mandatory)
2. location  (mandatory)
3. projectedLocation  (optional for stop point)
4. passengerId  (mandatory for stop point)
5. nationalId  (optional for stop point)



_Code quote:_
```Java
    private Point location;
    private Integer nationalId;
    private String passengerId;
    private Point projectedLocation;
    private RoutePointType type;
```
___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointType.java, line 10 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NJ0Ut-VWDKqpAQ0Id:-N-NJ0Ut-VWDKqpAQ0Ie:b-1p9i8k) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/RoutePointType.java#L10)):*
> ```Java
> public enum RoutePointType {
> 
>     OTHER,
> ```

Put this last.



_Code quote:_
```Java
OTHER,
```
___
*[src/main/resources/export/export_route_geometries.sql, line 8 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NOc9M2UboPS0qt_Tq:-N-NOc9M2UboPS0qt_Tr:bp7k70f) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/main/resources/export/export_route_geometries.sql#L8)):*
> ```TSQL
> FROM network.network_route_directions rdo
> CROSS JOIN LATERAL (
>     SELECT ST_GeomFromEWKB(ST_AsEWKB(ST_MakeLine(ST_Force2D(compound_geog::geometry)))) FROM (
> ```

The outermost function cancels the output of the second outermost function out.

It seems to me that you could remove the two outermost functions.



_Code quote:_
```TSQL
ST_GeomFromEWKB(ST_AsEWKB(
```
___
*[src/main/resources/export/export_route_geometries.sql, line 18 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NPswl2SZFSYtv-25W:-N-NPswl2SZFSYtv-25X:bl1kbc2) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/main/resources/export/export_route_geometries.sql#L18)):*
> ```TSQL
>         ORDER BY rl.network_route_link_order
>     ) links ) network_route_direction_shape
> WHERE network_route_direction_shape IS NOT NULL AND rdo.network_route_transmodel_id IS NOT NULL;
> ```

For clarity, I would rephrase the whole SQL query as:

```sql

SELECT
    rdo.network_route_direction_id AS route_direction_id,
    rdo.network_route_direction_ext_id as route_direction_ext_id,
    rdo.network_route_transmodel_id AS route_transmodel_id,
    route_geom
FROM network.network_route_directions rdo
CROSS JOIN LATERAL (
    SELECT ST_MakeLine(ST_Force2D(compound_geog::geometry)) AS route_geom
    FROM (
        SELECT coalesce(ls.infrastructure_link_shape, l.infrastructure_link_geog) AS compound_geog
        FROM network.network_route_directions rd
        INNER JOIN network.network_route_links rl ON rl.network_route_direction_id = rd.network_route_direction_id
        INNER JOIN infrastructure_network.infrastructure_links l ON l.infrastructure_link_id = rl.infrastructure_link_id
        LEFT JOIN infrastructure_network.infrastructure_link_shapes ls ON ls.infrastructure_link_id = l.infrastructure_link_id
        WHERE
            rd.network_route_direction_id = rdo.network_route_direction_id AND l.infrastructure_network_type = 'road'
        ORDER BY rl.network_route_link_order
    ) link_shape
) network_route_direction_shape
WHERE network_route_direction_shape IS NOT NULL AND rdo.network_route_transmodel_id IS NOT NULL;
```



_Code quote:_
```TSQL
WHERE network_route_direction_shape IS NOT NULL AND rdo.network_route_transmodel_id IS NOT NULL;
```
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportReaderTest.java, line 74 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NQtfCDqxq0NTpeRDM:-N-NQtfCDqxq0NTpeRDN:b80c0bv) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/test/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportReaderTest.java#L74)):*
> ```Java
>     class WhenSourceTablesHaveOneRoute {
> 
>         private final double EXPECTED_FIRST_ROUTE_COORDINATE_X = 24.457948;
> ```

`COORDINATE_LNG` since the value is called "longitude"



_Code quote:_
```Java
COORDINATE_X
```
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportReaderTest.java, line 75 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NQzny5spix2GGgYll:-N-NQzny5spix2GGgYlm:bgim2mw) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/test/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportReaderTest.java#L75)):*
> ```Java
> 
>         private final double EXPECTED_FIRST_ROUTE_COORDINATE_X = 2 [...]

2022-04-11 11:58 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: all files reviewed, 20 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)



<!-- Sent from Reviewable.io -->

2022-04-12 05:05 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 184 of 191 files reviewed, 20 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/resources/export/export_route_geometries.sql, line 8 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NOc9M2UboPS0qt_Tq:-N-R9AYSEhYa-JOs1xcJ:bi4e1lu) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/main/resources/export/export_route_geometries.sql#L8)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

The outermost function cancels the output of the second outermost function out.

It seems to me that you could remove the two outermost functions.
</blockquote></details>

Removed unnecessary functions.


<!-- Sent from Reviewable.io -->

2022-04-12 05:09 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 184 of 191 files reviewed, 20 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/resources/export/export_route_geometries.sql, line 18 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NPswl2SZFSYtv-25W:-N-RA1tjEvLQOpo24Jiq:b-8hb7m0) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/main/resources/export/export_route_geometries.sql#L18)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

For clarity, I would rephrase the whole SQL query as:

```sql

SELECT
    rdo.network_route_direction_id AS route_direction_id,
    rdo.network_route_direction_ext_id as route_direction_ext_id,
    rdo.network_route_transmodel_id AS route_transmodel_id,
    route_geom
FROM network.network_route_directions rdo
CROSS JOIN LATERAL (
    SELECT ST_MakeLine(ST_Force2D(compound_geog::geometry)) AS route_geom
    FROM (
        SELECT coalesce(ls.infrastructure_link_shape, l.infrastructure_link_geog) AS compound_geog
        FROM network.network_route_directions rd
        INNER JOIN network.network_route_links rl ON rl.network_route_direction_id = rd.network_route_direction_id
        INNER JOIN infrastructure_network.infrastructure_links l ON l.infrastructure_link_id = rl.infrastructure_link_id
        LEFT JOIN infrastructure_network.infrastructure_link_shapes ls ON ls.infrastructure_link_id = l.infrastructure_link_id
        WHERE
            rd.network_route_direction_id = rdo.network_route_direction_id AND l.infrastructure_network_type = 'road'
        ORDER BY rl.network_route_link_order
    ) link_shape
) network_route_direction_shape
WHERE network_route_direction_shape IS NOT NULL AND rdo.network_route_transmodel_id IS NOT NULL;
```
</blockquote></details>

I tried this query, but tests failed because the query didn't return any results.


<!-- Sent from Reviewable.io -->

2022-04-12 05:24 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 182 of 191 files reviewed, 20 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/test/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingServiceTest.java, line 283 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NTKT973x9VNcPteZt:-N-RDbUK4oWf9SyB2ZIa:bpy29p) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/test/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingServiceTest.java#L283)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

It would be more correct to use longitudes and latitudes in variable names since the values relate to spherical coordinate system, not a projected one with "x" and "y". The same issue appears in many test classes in this PR.
</blockquote></details>

changed X to LNG and Y to LAT.


<!-- Sent from Reviewable.io -->

2022-04-12 05:24 UTC, pkainulainen-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78)* status: 182 of 191 files reviewed, 20 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/test/java/fi/hsl/jore/importer/feature/mapmatching/service/RouteGeometryTestFactory.java, line 93 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NTkfZ978v6JkMaN7F:-N-RDiY5BQ4JJbTkOtxe:b-iw7ujc) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/test/java/fi/hsl/jore/importer/feature/mapmatching/service/RouteGeometryTestFactory.java#L93)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Not really optional in the target API.
</blockquote></details>

This is optional on this side of the fence because it's set only if the point is scheduled stop point.


<!-- Sent from Reviewable.io -->

2022-04-13 09:55 UTC, jarkkoka reviewed
Basically looks good. Some minor remarks left as comments. From my part, there is no need for a new review cycle unless you feel it is needed.

> Reviewed 2 of 2 files at r15, 4 of 5 files at r16, 2 of 2 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-:-N-XIk3Y--ZxmxPs_W6U:blw0cpo)* status: all files reviewed, 7 unresolved discussions (waiting on @jschummer, @pallost, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilder.java, line 62 at r18](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-WRejO5gwNCYYlh7he:-N-WRejO5gwNCYYlh7hf:b-djui08) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/47491aaa99e77c22db2c8336f71ee8cf2eec9e41/src/main/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilder.java#L62)):*
> ```Java
>             if (input.type() == NodeType.STOP) {
>                 routePoint.setNationalId(parseToNationalId(input.stopPointElyNumber()));
>                 routePoint.setPassengerId(input.stopPointShortId().orElse(null));
> ```

When route point is of type route stop point, then a null is not allowed in the map-matching API.



_Code quote:_
```Java
orElse(null)
```
___
*[src/main/resources/export/export_route_geometries.sql, line 18 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NPswl2SZFSYtv-25W:-N-WSMKf1E49dgiwlQf5:bbfug24) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/main/resources/export/export_route_geometries.sql#L18)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I tried this query, but tests failed because the query didn't return any results.
</blockquote></details>

Well, not critical to reformat the query. Fundamentally, there is not much difference. The main difference is to indent sub-queries more intuitively and renaming some things.

I also test the query I suggested and for me it returned non-empty result set when I removed `rdo.network_route_transmodel_id IS NOT NULL` from the last line because in my database there were no TM IDs.

However, on the last line there was also a logical error where in place of `network_route_direction_shape` there should have been `route_geom`.

I will leave it to your consideration, what would be the best solution here.
___
*[src/test/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilderTest.java, line 89 at r18](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-XH7HLExbGzqPsaISr:-N-XH7HLExbGzqPsaISs:b-7wc6ew) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/47491aaa99e77c22db2c8336f71ee8cf2eec9e41/src/test/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilderTest.java#L89)):*
> ```Java
>                     .as("startPointX")
>                     .isEqualTo(ROUTE_GEOMETRY_START_X);
>             softAssertions.assertThat(startPoint.getLatitude())
> ```

Not a critical issue but also in the file there are variable names with X's and Y's when actually those properties are longitudes and latitudes.



_Code quote:_
```Java
                    .as("startPointX")
                    .isEqualTo(ROUTE_GEOMETRY_START_X);
            softAssertions.assertThat(startPoint.getLatitude())
                    .as("startPointY")
                    .isEqualTo(ROUTE_GEOMETRY_START_Y);
```
___
*[src/test/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingServiceTest.java, line 455 at r18](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-XGFvn-feJ-KvwvpOc:-N-XGFvn-feJ-KvwvpOd:b-bvvly9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/47491aaa99e77c22db2c8336f71ee8cf2eec9e41/src/test/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingServiceTest.java#L455)):*
> ```Java
>                     final LngLatAlt coordinateOne = coordinates.get(0);
>                     softAssertions.assertThat(coordinateOne.getLongitude())
>                             .as("coordinateOneX")
> ```

Minor inconsistency: description texts not changed accordingly.



_Code quote:_
```Java
X
```
___
*[src/test/java/fi/hsl/jore/importer/feature/mapmatching/service/RouteGeometryTestFactory.java, line 93 at r14](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/78#-N-NTkfZ978v6JkMaN7F:-N-XGWHJ8dV_YCJ5nhg5:b2nhll9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3065436450039ffa3a629ea1d7b9cbbc4ca4481/src/test/java/fi/hsl/jore/importer/feature/mapmatching/service/RouteGeometryTestFactory.java#L93)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

This is optional on this side of the fence because it's set only if the point is scheduled stop point.
</blockquote></details>

Ok.


<!-- Sent from Reviewable.io -->

2022-04-13 10:58 UTC, merged