Rename dto interfaces
HSLdevcom/jore4-jore3-importer pull request #97
Opened 2022-10-05 11:46 UTC by culka

Renames DTO interfaces:

Importable => Jore3
Exportable => Importer
Transmodel => Jore4

Resolves HSLdevcom/jore4#724

2022-10-17 15:45 UTC, jarkkoka requested changes
> Reviewed 171 of 171 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97)* status: all files reviewed, 62 unresolved discussions (waiting on @culka)

___
*[`src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java` line 81 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEZs5PCE2wRDMSd4PPz:-NEZs5PCE2wRDMSd4PQ-:bf6l97a) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java#L81)):*
> ```Java
> import fi.hsl.jore.importer.feature.network.scheduled_stop_point.dto.ImporterScheduledStopPoint;
> import fi.hsl.jore.importer.feature.network.scheduled_stop_point.dto.Jore3ScheduledStopPoint;
> import fi.hsl.jore.importer.feature.jore4.entity.Jore4JourneyPattern;
> ```

Obviously, the package names are not alphabetically sorted anymore. Could be laborous to fix since the PR changes 170 files.



_Code quote:_
```Java
import fi.hsl.jore.importer.feature.jore4.entity.Jore4JourneyPattern;
```
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/line/LineExportWriter.java` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaKqhD18KdsWYC5WHZ:-NEaKqhD18KdsWYC5WH_:b-pi8nah) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/line/LineExportWriter.java#L33)):*
> ```Java
>         jore4Repository.insert(items);
> 
>         final io.vavr.collection.List<PersistableLineIdMapping> transmodelIdMappings = items.stream()
> ```

jore4IdMappings



_Code quote:_
```Java
transmodelIdMappings
```
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route/JourneyPatternExportMapper.java` line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaCLrY7ca4KFR0B_wY:-NEaCLrY7ca4KFR0B_wZ:bchrkau) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route/JourneyPatternExportMapper.java#L23)):*
> ```Java
>         return ImporterJourneyPattern.of(
>                 UUID.fromString(resultSet.getString("route_direction_id")),
>                 UUID.fromString(resultSet.getString("route_transmodel_id"))
> ```

Would it be too tedious to rename this to `route_jore4_id`?



_Code quote:_
```Java
route_transmodel_id
```
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route/JourneyPatternStopExportMapper.java` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaDCV90GpxBFlWuYz3:-NEaDCV90GpxBFlWuYz4:bvvqgks) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route/JourneyPatternStopExportMapper.java#L33)):*
> ```Java
>                 resultSet.getBoolean("is_via_point"),
>                 Optional.ofNullable(resultSet.getString("via_names")).map(viaNames -> jsonConverter.fromJson(viaNames, MultilingualString.class)),
>                 UUID.fromString(resultSet.getString("journey_pattern_transmodel_id")),
> ```

Is is too tedious to replace "transmodel" with "jore4" in the column name?



_Code quote:_
```Java
journey_pattern_transmodel_id
```
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteExportMapper.java` line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaE0U215GpMur_r1Ku:-NEaE0U215GpMur_r1Kv:bpxh7do) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteExportMapper.java#L34)):*
> ```Java
>                 DirectionType.of(resultSet.getString("direction_type")),
>                 jsonConverter.fromJson(resultSet.getString("name"), MultilingualString.class),
>                 UUID.fromString(resultSet.getString("line_transmodel_id")),
> ```

Is is possible to replace "transmodel" with "jore4" in the column name?



_Code quote:_
```Java
line_transmodel_id
```
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteExportWriter.java` line 30 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaEQHPACnavJyBzcU3:-NEaEQHQAFQPVAnFuNfS:b3g8oxe) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteExportWriter.java#L30)):*
> ```Java
>         jore4Repository.insert(items);
> 
>         final io.vavr.collection.List<PersistableRouteIdMapping> transmodelIdMappings = items.stream()
> ```

Rename to `jore4IdMappings`.



_Code quote:_
```Java
transmodelIdMappings
```
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportMapper.java` line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaEkQu8xdDtR05mmEy:-NEaEkQu8xdDtR05mmEz:b-jcxutl) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportMapper.java#L32)):*
> ```Java
>                 UUID.fromString(resultSet.getString("route_direction_id")),
>                 resultSet.getString("route_direction_ext_id"),
>                 UUID.fromString(resultSet.getString("route_transmodel_id"))
> ```

Can "transmodel" be replaced by "jore4" in the column name (without too much effort involved)?



_Code quote:_
```Java
route_transmodel_id
```
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route_direction/support/IRouteDirectionImportRepository.java` line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaFKrqCBLOJVpCNL6G:-NEaFKrqCBLOJVpCNL6H:b-85vkzt) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route_direction/support/IRouteDirectionImportRepository.java#L16)):*
> ```Java
>      * the Jore 4 database.
>      *
>      * @param idMappings    The information that's required to set the transmodel ids
> ```

Jore4



_Code quote:_
```Java
transmodel
```
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route_direction/support/IRouteDirectionImportRepository.java` line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaNImyDa_1e05Tp1CM:-NEaNImyDa_1e05Tp1CN:bynjahw) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route_direction/support/IRouteDirectionImportRepository.java#L19)):*
> ```Java
>      *                      of journey patterns.
>      */
>     void setJourneyPatternTransmodelIds(List<PersistableJourneyPatternIdMapping> idMappings);
> ```

Rename to `setJourneyPatternJore4Ids`.



_Code quote:_
```Java
setJourneyPatternTransmodelIds
```
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route_direction/support/IRouteDirectionImportRepository.java` line 25 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaFQZy46nsFK7aW9lG:-NEaFQZy46nsFK7aW9lH:b-85vkzt) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route_direction/support/IRouteDirectionImportRepository.java#L25)):*
> ```Java
>      * the Jore 4 database.
>      *
>      * @param   idMappings   The information that's required to set the transmodel ids
> ```

Jore4



_Code quote:_
```Java
transmodel
```
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route_direction/support/IRouteDirectionImportRepository.java` line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaNPdm0BiU3uUJkeCW:-NEaNPdm0BiU3uUJkeCX:b-666o2f) ([raw file](https://github.com/hsldevcom [...]

2022-10-17 15:49 UTC, jarkkoka requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97)* status: all files reviewed, 62 unresolved discussions (waiting on @culka)

___
*[`src/test/java/fi/hsl/jore/importer/config/jobs/ExportRouteStepTest.java` line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEa_5wT4k7wLB5c5_wP:-NEacODyBLx3Asu1iQYT:bc4rif4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/test/java/fi/hsl/jore/importer/config/jobs/ExportRouteStepTest.java#L56)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Rename to `EXPECTED_LINE_TRANSMODEL_ID`.
</blockquote></details>

Oops, typo. Meant to request that `EXPECTED_LINE_TRANSMODEL_ID` is renamed to `EXPECTED_LINE_JORE4_ID`.


<!-- Sent from Reviewable.io -->

2022-10-18 06:31 UTC, jarkkoka requested changes
Found many method names and variables still occupying "Transmodel" word. IMO these should be fixed in this same PR in order to have consistent terminology in the codebase.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-:-NEdm74U-XHMijfj00YP:brp7ehz)* status: all files reviewed, 62 unresolved discussions (waiting on @culka)

___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route/JourneyPatternExportMapper.java` line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaCLrY7ca4KFR0B_wY:-NEdlWHfELL6d_ip1uvY:b-efwi8u) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route/JourneyPatternExportMapper.java#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Would it be too tedious to rename this to `route_jore4_id`?
</blockquote></details>

Follow-up: Could be done in a later PR since this probably involves additional db migration scripts.
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route/JourneyPatternStopExportMapper.java` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaDCV90GpxBFlWuYz3:-NEdlfDv4To_ya4q_-yB:b-libdqw) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route/JourneyPatternStopExportMapper.java#L33)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Is is too tedious to replace "transmodel" with "jore4" in the column name?
</blockquote></details>

Follow-up: Could be done in a later PR since this probably involves additional db migration scripts.
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteExportMapper.java` line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaE0U215GpMur_r1Ku:-NEdlhHX32dqSyfzmEX3:b-efwi8u) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteExportMapper.java#L34)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Is is possible to replace "transmodel" with "jore4" in the column name?
</blockquote></details>

Follow-up: Could be done in a later PR since this probably involves additional db migration scripts.
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportMapper.java` line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaEkQu8xdDtR05mmEy:-NEdlj5s6iP05gJJzLBZ:b-efwi8u) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportMapper.java#L32)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Can "transmodel" be replaced by "jore4" in the column name (without too much effort involved)?
</blockquote></details>

Follow-up: Could be done in a later PR since this probably involves additional db migration scripts.


<!-- Sent from Reviewable.io -->

2023-02-03 08:52 UTC, Leitsi requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97)* status: all files reviewed, 62 unresolved discussions (waiting on @culka and @jarkkoka)

___
*[`src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java` line 81 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEZs5PCE2wRDMSd4PPz:-NN2nICY6wmMDZru2Mzb:bxttuyj) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java#L81)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Obviously, the package names are not alphabetically sorted anymore. Could be laborous to fix since the PR changes 170 files.
</blockquote></details>

Seems that Idea's "Optimize Imports" action can be invoked for the whole project, making this trivial. Does other stuff than just ordering as well, but seemed fine.

Ideally this kind of thing would be evaluated / fixable by a linter, otherwise we should mainly ignore these I think.
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/line/LineExportWriter.java` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaKqhD18KdsWYC5WHZ:-NNLQvINElSpNVXv_zZn:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/line/LineExportWriter.java#L33)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

jore4IdMappings
</blockquote></details>

Done.
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route/JourneyPatternExportMapper.java` line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaCLrY7ca4KFR0B_wY:-NNLQyFL9idW0VPWGPSn:bqf6e2i) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route/JourneyPatternExportMapper.java#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Follow-up: Could be done in a later PR since this probably involves additional db migration scripts.
</blockquote></details>

Done. Same with other similar issues. Fixed in this same PR but separate commit.
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportMapper.java` line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaEkQu8xdDtR05mmEy:-NNLR67kDxJgFGpgAp7Q:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteGeometryExportMapper.java#L32)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Follow-up: Could be done in a later PR since this probably involves additional db migration scripts.
</blockquote></details>

Done.
___
*[`src/test/java/fi/hsl/jore/importer/config/jobs/ExportLineStepTest.java` line 149 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaZbkL3yDOw1lI-Pmw:-NNLRiu3-kFebIzAV1Id:b-rbz6q2) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/test/java/fi/hsl/jore/importer/config/jobs/ExportLineStepTest.java#L149)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Replace two occurrences of "Transmodel" word with "Jore4".
</blockquote></details>

All of these should be fixed now.
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route_link/dto/Jore3RoutePointsAndLinks.java` line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/97#-NEaFw_yDb1E5XWpwzJL:-NN5Z_-B9N-nq1-Z-_kM:b-kc32sp) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route_link/dto/Jore3RoutePointsAndLinks.java#L10)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Extra indent before interface name
</blockquote></details>

Fixed.

Again, would be neat if we had some linter / prettier in place so we could just ignore this kind of things in review.



_Code quote:_
```Java
Jore3RoutePointsAndLinks
```


<!-- Sent from Reviewable.io -->

2023-02-03 16:16 UTC, jarkkoka approved these changes
Very nice work! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 37 of 62 files at r2, 187 of 187 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/97#-:-NNN34oR4amjEPSjfGkI:b-hi67zu)* status: all files reviewed, 13 unresolved discussions (waiting on @culka and @Leitsi)

___
*[`-- commits` line 17 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/97#-NNMpIDP424m7Z5qoiKx):*
Nicely detailed commit messaged. :+1: 



_Code quote:_
```
  Removes unused imports, orders them properly, and uses * imports consistently
  (= not at all).
  Done by applying Ideas "Optimize Imports" to the whole project.
  With default settings except 'Class counts to use imports with "*"' and
  'Names count to use static import with "*"' set to 999 to avoid triggering them.
  These can be find in Idea -> Settings -> Editor -> Code Style -> Java -> Imports
```
___
*[`src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java` line 81 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/97#-NEZs5PCE2wRDMSd4PPz:-NNMqPT-6Ti3oMWCY6GO:bini2uk) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java#L81)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Seems that Idea's "Optimize Imports" action can be invoked for the whole project, making this trivial. Does other stuff than just ordering as well, but seemed fine.

Ideally this kind of thing would be evaluated / fixable by a linter, otherwise we should mainly ignore these I think.
</blockquote></details>

Nice!

It is part of our code style/convention that unnecessary imports are not left in the code. IDEA, by default, reports these as warnings so we should not ignore them in order to have clean code.
___
*[`src/test/java/fi/hsl/jore/importer/config/jobs/ExportJourneyPatternsStepTest.java` line 23 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/97#-NNMzr636sla7wGFuF7v:-NNMzr636sla7wGFuF7w:b-ijtffe) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/ca4b356562ba93ce6cb6c37584c7600d25c1b449/src/test/java/fi/hsl/jore/importer/config/jobs/ExportJourneyPatternsStepTest.java#L23)):*
> ```Java
>         "/sql/importer/drop_tables.sql",
>         "/sql/importer/populate_infrastructure_nodes.sql",
>         "/sql/importer/populate_lines_with_jore4_ids.sql",
> ```

For me, reading this makes now more sense. :+1: 



_Code quote:_
```Java
        "/sql/importer/drop_tables.sql",
        "/sql/importer/populate_infrastructure_nodes.sql",
        "/sql/importer/populate_lines_with_jore4_ids.sql",
        "/sql/importer/populate_routes.sql",
        "/sql/importer/populate_route_directions_with_jore4_ids.sql"
})
@Sql(
        scripts = {
                "/sql/jore4/drop_tables.sql",
                "/sql/jore4/populate_infrastructure_links.sql",
                "/sql/jore4/populate_lines.sql",
                "/sql/jore4/populate_scheduled_stop_points.sql",
                "/sql/jore4/populate_routes.sql"
```
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route_link/dto/Jore3RoutePointsAndLinks.java` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/97#-NEaFw_yDb1E5XWpwzJL:-NNMy00SARfl7280J6ym:b-jk9784) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/f3da5666ff6d8e61de53165a4917c5ed28602406/src/main/java/fi/hsl/jore/importer/feature/batch/route_link/dto/Jore3RoutePointsAndLinks.java#L10)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Fixed.

Again, would be neat if we had some linter / prettier in place so we could just ignore this kind of things in review.
</blockquote></details>

Maybe some IDEA "save action" that automatically formats the code while saving.


<!-- Sent from Reviewable.io -->

2023-02-06 10:34 UTC, Leitsi approved these changes

2023-02-06 10:54 UTC, merged